package = "com.sora.showcase"
includes = ["schema/game.toml"]

[build]
data_format = "xlsx"
data_root = "data"
schema_lock = "generated/schema.lock"
excel_templates = "generated/excel"

[[build.codegen]]
target = "rust"
out = "rust/src/generated"

[[build.codegen]]
target = "kotlin"
out = "kotlin/src/generated/kotlin"

[[build.codegen]]
target = "csharp"
out = "csharp/src/generated/csharp"

[[build.codegen]]
target = "java"
out = "java/src/generated/java"

[[build.codegen]]
target = "go"
out = "go/internal/showcase"

[[build.codegen]]
target = "lua"
out = "lua/generated"

[[build.codegen]]
target = "proto"
out = "generated/proto"

[[build.exports]]
format = "binary"
out = "generated/config.sora"

[[build.exports]]
format = "json"
out = "generated/config.json"

[[build.exports]]
format = "protobuf"
out = "generated/config.pb"

[[build.exports]]
format = "typed-protobuf"
out = "generated/config.typed.pb"

[[build.exports]]
format = "cbor"
out = "generated/config.cbor"

[[build.exports]]
format = "json-debug"
out = "generated/debug-json"

[codegen.rust]
runtime_format = "sora"
map_type = "fx_hash_map"

[codegen.kotlin]
runtime_format = "sora"

[codegen.csharp]
runtime_format = "sora"

[codegen.java]
runtime_format = "sora"

[codegen.go]
runtime_format = "sora"

[codegen.lua]
runtime_format = "sora"
module = "generated"
lua_version = "5.4"
enum_repr = "string"
