name = "client"
contract = "com.sora.showcase/client"
groups = ["common"]

[bindings.kotlin]
package = "com.sora.showcase"

[bindings.csharp]
namespace = "com.sora.showcase"

[bindings.java]
package = "com.sora.showcase"

[bindings.scala]
package = "com.sora.showcase"

[bindings.go]
package = "showcase"

[bindings.c]
prefix = "sora_showcase"

[bindings.cpp]
namespace = "sora::showcase"

[bindings.proto-schema]
package = "com.sora.showcase"

[bindings.lua]
module = "generated"
