// This file was generated by Sora. Do not edit manually.

package showcase

type Buff struct {
    Id int32
    Name string
    Duration float32
    Modifiers []StatModifier
}

func decodeBuff(reader *SoraReader) (Buff, error) {
    var value Buff
    var err error
    value.Id, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Name, err = reader.ReadString()
    if err != nil {
        return value, err
    }
    value.Duration, err = reader.ReadFloat32()
    if err != nil {
        return value, err
    }
    value.Modifiers, err = ReadList(reader, func(reader *SoraReader) (StatModifier, error) { return decodeStatModifier(reader) })
    if err != nil {
        return value, err
    }
    return value, nil
}

type BuffTable struct {
    rows map[int32]Buff
}

func buildBuffTable(rows []Buff) (*BuffTable, error) {
    return &BuffTable{rows: DecodeMapTable(rows, func(row Buff) int32 { return row.Id })}, nil
}

func decodeBuffTable(bundle *SoraBundle) (*BuffTable, error) {
    rows, err := DecodeTable(bundle, "Buff", decodeBuff)
    if err != nil {
        return nil, err
    }
    return buildBuffTable(rows)
}

func (table *BuffTable) Rows() map[int32]Buff {
    return table.rows
}
func (table *BuffTable) Get(key int32) (Buff, bool) {
    value, ok := table.rows[key]
    return value, ok
}
func (table *BuffTable) Name() string {
    return "Buff"
}

func (table *BuffTable) Mode() SoraTableMode {
    return SoraTableModeMap
}

func (table *BuffTable) Key() string {
    return "id"
}

func (table *BuffTable) RowType() string {
    return "Buff"
}

func (table *BuffTable) Len() int {
    return len(table.rows)
}
