// This file was generated by Sora. Do not edit manually.

package showcase

type Buff struct {
	Id        int32
	Name      string
	Duration  float32
	Modifiers []StatModifier
}

func decodeBuff(reader *SoraReader) (Buff, error) {
	var value Buff
	var err error
	value.Id, err = reader.ReadInt32()
	if err != nil {
		return value, err
	}
	value.Name, err = reader.ReadString()
	if err != nil {
		return value, err
	}
	value.Duration, err = reader.ReadFloat32()
	if err != nil {
		return value, err
	}
	value.Modifiers, err = ReadList(reader, func(reader *SoraReader) (StatModifier, error) { return decodeStatModifier(reader) })
	if err != nil {
		return value, err
	}
	return value, nil
}

func decodeBuffValue(input SoraValue) (Buff, error) {
	var value Buff
	obj, err := input.AsObject()
	if err != nil {
		return value, err
	}
	value.Id, err = obj.Get("id").AsInt32()
	if err != nil {
		return value, err
	}
	value.Name, err = obj.Get("name").AsString()
	if err != nil {
		return value, err
	}
	value.Duration, err = obj.Get("duration").AsFloat32()
	if err != nil {
		return value, err
	}
	value.Modifiers, err = DecodeSoraValueList(obj.Get("modifiers"), func(item SoraValue) (StatModifier, error) { return decodeStatModifierValue(item) })
	if err != nil {
		return value, err
	}
	return value, nil
}

type BuffTable struct {
	rows map[int32]Buff
	keys []int32
}

func buildBuffTable(rows []Buff) (*BuffTable, error) {
	keys := make([]int32, 0, len(rows))
	for _, row := range rows {
		keys = append(keys, row.Id)
	}
	return &BuffTable{rows: DecodeMapTable(rows, func(row Buff) int32 { return row.Id }), keys: keys}, nil
}

func decodeBuffTable(source SoraTableSource) (*BuffTable, error) {
	rows, err := DecodeSourceTable(source, "Buff", decodeBuff, decodeBuffValue)
	if err != nil {
		return nil, err
	}
	return buildBuffTable(rows)
}

func (table *BuffTable) Rows() map[int32]Buff {
	return table.rows
}
func (table *BuffTable) Get(key int32) (Buff, bool) {
	value, ok := table.rows[key]
	return value, ok
}

func (table *BuffTable) Keys() []int32 {
	return table.keys
}

func (table *BuffTable) OrderedRows() []Buff {
	rows := make([]Buff, 0, len(table.keys))
	for _, key := range table.keys {
		if row, ok := table.rows[key]; ok {
			rows = append(rows, row)
		}
	}
	return rows
}
func (table *BuffTable) Name() string {
	return "Buff"
}

func (table *BuffTable) Mode() SoraTableMode {
	return SoraTableModeMap
}

func (table *BuffTable) Key() string {
	return "id"
}

func (table *BuffTable) RowType() string {
	return "Buff"
}

func (table *BuffTable) Len() int {
	return len(table.rows)
}
