// This file was generated by Sora. Do not edit manually.

package showcase

type Buff struct {
    Id int32
    Name string
    Duration float32
    Modifiers []StatModifier
}

func decodeBuff(reader *SoraReader) (Buff, error) {
    var value Buff
    var err error
    value.Id, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Name, err = reader.ReadString()
    if err != nil {
        return value, err
    }
    value.Duration, err = reader.ReadFloat32()
    if err != nil {
        return value, err
    }
    value.Modifiers, err = ReadList(reader, func(reader *SoraReader) (StatModifier, error) { return decodeStatModifier(reader) })
    if err != nil {
        return value, err
    }
    return value, nil
}
