// This file was generated by Sora. Do not edit manually.

package showcase

type Character struct {
    Id int32
    Name string
    Rarity Rarity
    BaseLevel int32
    BaseSkill int32
    StarterItems []int32
    SpawnPos Vec3
}

func decodeCharacter(reader *SoraReader) (Character, error) {
    var value Character
    var err error
    value.Id, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Name, err = reader.ReadString()
    if err != nil {
        return value, err
    }
    value.Rarity, err = decodeRarity(reader)
    if err != nil {
        return value, err
    }
    value.BaseLevel, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.BaseSkill, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.StarterItems, err = ReadList(reader, func(reader *SoraReader) (int32, error) { return reader.ReadInt32() })
    if err != nil {
        return value, err
    }
    value.SpawnPos, err = decodeVec3(reader)
    if err != nil {
        return value, err
    }
    return value, nil
}

type CharacterTable struct {
    rows map[int32]Character
}

func buildCharacterTable(rows []Character) (*CharacterTable, error) {
    return &CharacterTable{rows: DecodeMapTable(rows, func(row Character) int32 { return row.Id })}, nil
}

func decodeCharacterTable(bundle *SoraBundle) (*CharacterTable, error) {
    rows, err := DecodeTable(bundle, "Character", decodeCharacter)
    if err != nil {
        return nil, err
    }
    return buildCharacterTable(rows)
}

func (table *CharacterTable) Rows() map[int32]Character {
    return table.rows
}
func (table *CharacterTable) Get(key int32) (Character, bool) {
    value, ok := table.rows[key]
    return value, ok
}
func (table *CharacterTable) Name() string {
    return "Character"
}

func (table *CharacterTable) Mode() SoraTableMode {
    return SoraTableModeMap
}

func (table *CharacterTable) Key() string {
    return "id"
}

func (table *CharacterTable) RowType() string {
    return "Character"
}

func (table *CharacterTable) Len() int {
    return len(table.rows)
}
