// This file was generated by Sora. Do not edit manually.

package showcase

type ComplexBudget struct {
	Fixed  ResourceCost
	Random []RewardBundle
	Limits map[string]int32
}

func decodeComplexBudget(reader *SoraReader) (ComplexBudget, error) {
	var value ComplexBudget
	var err error
	value.Fixed, err = decodeResourceCost(reader)
	if err != nil {
		return value, err
	}
	value.Random, err = ReadList(reader, func(reader *SoraReader) (RewardBundle, error) { return decodeRewardBundle(reader) })
	if err != nil {
		return value, err
	}
	value.Limits, err = ReadMap(reader, func(reader *SoraReader) (string, error) { return reader.ReadString() }, func(reader *SoraReader) (int32, error) { return reader.ReadInt32() })
	if err != nil {
		return value, err
	}
	return value, nil
}

func decodeComplexBudgetValue(input SoraValue) (ComplexBudget, error) {
	var value ComplexBudget
	obj, err := input.AsObject()
	if err != nil {
		return value, err
	}
	value.Fixed, err = decodeResourceCostValue(obj.Get("fixed"))
	if err != nil {
		return value, err
	}
	value.Random, err = DecodeSoraValueList(obj.Get("random"), func(item SoraValue) (RewardBundle, error) { return decodeRewardBundleValue(item) })
	if err != nil {
		return value, err
	}
	value.Limits, err = DecodeSoraValueMap(obj.Get("limits"), func(item SoraValue) (string, error) { return item.AsString() }, func(item SoraValue) (int32, error) { return item.AsInt32() })
	if err != nil {
		return value, err
	}
	return value, nil
}

func (value ComplexBudget) collectTextKeys(out *[]TextKey) {
	value.Fixed.collectTextKeys(out)
	for _, item := range value.Random {
		item.collectTextKeys(out)
	}
}
