// This file was generated by Sora. Do not edit manually.

package showcase

type ComplexConditionGroup struct {
    Id int32
    Name string
    // Conditions: A derived list of union values; each child row is edited without JSON
    Conditions []EventCondition
}

func decodeComplexConditionGroup(reader *SoraReader) (ComplexConditionGroup, error) {
    var value ComplexConditionGroup
    var err error
    value.Id, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Name, err = reader.ReadString()
    if err != nil {
        return value, err
    }
    value.Conditions, err = ReadList(reader, func(reader *SoraReader) (EventCondition, error) { return decodeEventCondition(reader) })
    if err != nil {
        return value, err
    }
    return value, nil
}

func decodeComplexConditionGroupValue(input SoraValue) (ComplexConditionGroup, error) {
    var value ComplexConditionGroup
    obj, err := input.AsObject()
    if err != nil {
        return value, err
    }
    value.Id, err = obj.Get("id").AsInt32()
    if err != nil {
        return value, err
    }
    value.Name, err = obj.Get("name").AsString()
    if err != nil {
        return value, err
    }
    value.Conditions, err = DecodeSoraValueList(obj.Get("conditions"), func(item SoraValue) (EventCondition, error) { return decodeEventConditionValue(item) })
    if err != nil {
        return value, err
    }
    return value, nil
}

const complexConditionGroupTableName = "ComplexConditionGroup"

var complexConditionGroupTableInfo = SoraTableInfo{
    Name: complexConditionGroupTableName,
    RowType: "ComplexConditionGroup",
    Shape: SoraTableShapeKeyed,
    PrimaryKey: &SoraKeyInfo{Name: "id", Type: "int32"},
    Indexes: []SoraIndexInfo{
    },
}

type ComplexConditionGroupTable struct {
    keys []int32
    rows map[int32]ComplexConditionGroup
}

func buildComplexConditionGroupTable(rows []ComplexConditionGroup) (*ComplexConditionGroupTable, error) {
    keys := make([]int32, 0, len(rows))
    for _, row := range rows {
        keys = append(keys, row.Id)
    }
    return &ComplexConditionGroupTable{keys: keys, rows: DecodeMapTable(rows, func(row ComplexConditionGroup) int32 { return row.Id })}, nil
}

func decodeComplexConditionGroupTable(source SoraTableSource) (*ComplexConditionGroupTable, error) {
    rows, err := DecodeSourceTable(source, complexConditionGroupTableName, decodeComplexConditionGroup, decodeComplexConditionGroupValue)
    if err != nil {
        return nil, err
    }
    return buildComplexConditionGroupTable(rows)
}

func (table *ComplexConditionGroupTable) Rows() map[int32]ComplexConditionGroup {
    return table.rows
}
func (table *ComplexConditionGroupTable) Get(key int32) (ComplexConditionGroup, bool) {
    value, ok := table.rows[key]
    return value, ok
}

func (table *ComplexConditionGroupTable) Keys() []int32 {
    return table.keys
}

func (table *ComplexConditionGroupTable) OrderedRows() []ComplexConditionGroup {
    rows := make([]ComplexConditionGroup, 0, len(table.keys))
    for _, key := range table.keys {
        if row, ok := table.rows[key]; ok {
            rows = append(rows, row)
        }
    }
    return rows
}
func (table *ComplexConditionGroupTable) Info() SoraTableInfo {
    return complexConditionGroupTableInfo
}

func (table *ComplexConditionGroupTable) Len() int {
    return len(table.rows)
}
