// This file was generated by Sora. Do not edit manually.

package showcase

type ComplexRuleCondition struct {
    ID int32
    RuleID int32
    Value EventCondition
}

func decodeComplexRuleCondition(reader *SoraReader) (ComplexRuleCondition, error) {
    var value ComplexRuleCondition
    var err error
    value.ID, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.RuleID, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Value, err = decodeEventCondition(reader)
    if err != nil {
        return value, err
    }
    return value, nil
}

func decodeComplexRuleConditionValue(input SoraValue) (ComplexRuleCondition, error) {
    var value ComplexRuleCondition
    obj, err := input.AsObject()
    if err != nil {
        return value, err
    }
    value.ID, err = obj.Get("id").AsInt32()
    if err != nil {
        return value, err
    }
    value.RuleID, err = obj.Get("rule_id").AsInt32()
    if err != nil {
        return value, err
    }
    value.Value, err = decodeEventConditionValue(obj.Get("value"))
    if err != nil {
        return value, err
    }
    return value, nil
}

func (value ComplexRuleCondition) collectTextKeys(out *[]TextKey) {
    collectEventConditionTextKeys(value.Value, out)
}

const complexRuleConditionTableName = "ComplexRuleCondition"

var complexRuleConditionTableInfo = SoraTableInfo{
    Name: complexRuleConditionTableName,
    RowType: "ComplexRuleCondition",
    Shape: SoraTableShapeKeyed,
    PrimaryKey: &SoraKeyInfo{Name: "id", Type: "int32"},
    Indexes: []SoraIndexInfo{
    },
}

type ComplexRuleConditionTable struct {
    keys []int32
    rows map[int32]ComplexRuleCondition
}

func buildComplexRuleConditionTable(rows []ComplexRuleCondition) (*ComplexRuleConditionTable, error) {
    keys := make([]int32, 0, len(rows))
    for _, row := range rows {
        keys = append(keys, row.ID)
    }
    return &ComplexRuleConditionTable{keys: keys, rows: DecodeMapTable(rows, func(row ComplexRuleCondition) int32 { return row.ID })}, nil
}

func decodeComplexRuleConditionTable(source SoraTableSource) (*ComplexRuleConditionTable, error) {
    rows, err := DecodeSourceTable(source, complexRuleConditionTableName, decodeComplexRuleCondition, decodeComplexRuleConditionValue)
    if err != nil {
        return nil, err
    }
    return buildComplexRuleConditionTable(rows)
}
func (table *ComplexRuleConditionTable) Rows() map[int32]ComplexRuleCondition {
    rows := make(map[int32]ComplexRuleCondition, len(table.rows))
    for key, row := range table.rows {
        rows[key] = row
    }
    return rows
}
func (table *ComplexRuleConditionTable) Get(key int32) (ComplexRuleCondition, bool) {
    value, ok := table.rows[key]
    return value, ok
}

func (table *ComplexRuleConditionTable) Keys() []int32 {
    return append([]int32(nil), table.keys...)
}

func (table *ComplexRuleConditionTable) OrderedRows() []ComplexRuleCondition {
    rows := make([]ComplexRuleCondition, 0, len(table.keys))
    for _, key := range table.keys {
        if row, ok := table.rows[key]; ok {
            rows = append(rows, row)
        }
    }
    return rows
}
func (table *ComplexRuleConditionTable) Info() SoraTableInfo {
    return complexRuleConditionTableInfo
}

func (table *ComplexRuleConditionTable) Len() int {
    return len(table.rows)
}
