// This file was generated by Sora. Do not edit manually.

package showcase

import "fmt"

const SoraSchemaFingerprint = "7e14f0cc1d24d238"

type SoraTableShape int

const (
	SoraTableShapeList SoraTableShape = iota
	SoraTableShapeKeyed
	SoraTableShapeSingleton
)

type SoraKeyInfo struct {
	Name string
	Type string
}

type SoraIndexInfo struct {
	Name   string
	Unique bool
	Fields []string
}

type SoraTableInfo struct {
	Name       string
	RowType    string
	Shape      SoraTableShape
	PrimaryKey *SoraKeyInfo
	Indexes    []SoraIndexInfo
}

type SoraTable interface {
	Info() SoraTableInfo
	Len() int
}

type SoraKeyedTable[K comparable, R any] interface {
	SoraTable
	Get(K) (R, bool)
	Keys() []K
	OrderedRows() []R
}

type SoraListTable[R any] interface {
	SoraTable
	Rows() []R
}

type SoraSingleTable[R any] interface {
	SoraTable
	Row() R
}

type SoraConfig struct {
	tables map[string]SoraTable
}

func NewSoraConfigFromSource(source SoraTableSource) (*SoraConfig, error) {
	schemaFingerprint, err := source.SchemaFingerprint()
	if err != nil {
		return nil, err
	}
	if schemaFingerprint != SoraSchemaFingerprint {
		return nil, fmt.Errorf("schema fingerprint mismatch: generated code expects %s, bundle contains %s", SoraSchemaFingerprint, schemaFingerprint)
	}
	tables := make(map[string]SoraTable, 34)
	itemTable, err := decodeItemTable(source)
	if err != nil {
		return nil, err
	}
	tables[itemTableName] = itemTable
	shopTable, err := decodeShopTable(source)
	if err != nil {
		return nil, err
	}
	tables[shopTableName] = shopTable
	shopItemTable, err := decodeShopItemTable(source)
	if err != nil {
		return nil, err
	}
	tables[shopItemTableName] = shopItemTable
	recipeTable, err := decodeRecipeTable(source)
	if err != nil {
		return nil, err
	}
	tables[recipeTableName] = recipeTable
	gachaPoolTable, err := decodeGachaPoolTable(source)
	if err != nil {
		return nil, err
	}
	tables[gachaPoolTableName] = gachaPoolTable
	gachaItemTable, err := decodeGachaItemTable(source)
	if err != nil {
		return nil, err
	}
	tables[gachaItemTableName] = gachaItemTable
	equipmentSetTable, err := decodeEquipmentSetTable(source)
	if err != nil {
		return nil, err
	}
	tables[equipmentSetTableName] = equipmentSetTable
	skillTable, err := decodeSkillTable(source)
	if err != nil {
		return nil, err
	}
	tables[skillTableName] = skillTable
	characterTable, err := decodeCharacterTable(source)
	if err != nil {
		return nil, err
	}
	tables[characterTableName] = characterTable
	characterSkillTable, err := decodeCharacterSkillTable(source)
	if err != nil {
		return nil, err
	}
	tables[characterSkillTableName] = characterSkillTable
	buffTable, err := decodeBuffTable(source)
	if err != nil {
		return nil, err
	}
	tables[buffTableName] = buffTable
	dropGroupTable, err := decodeDropGroupTable(source)
	if err != nil {
		return nil, err
	}
	tables[dropGroupTableName] = dropGroupTable
	dropEntryTable, err := decodeDropEntryTable(source)
	if err != nil {
		return nil, err
	}
	tables[dropEntryTableName] = dropEntryTable
	monsterTable, err := decodeMonsterTable(source)
	if err != nil {
		return nil, err
	}
	tables[monsterTableName] = monsterTable
	stageTable, err := decodeStageTable(source)
	if err != nil {
		return nil, err
	}
	tables[stageTableName] = stageTable
	stageRewardTable, err := decodeStageRewardTable(source)
	if err != nil {
		return nil, err
	}
	tables[stageRewardTableName] = stageRewardTable
	dungeonTable, err := decodeDungeonTable(source)
	if err != nil {
		return nil, err
	}
	tables[dungeonTableName] = dungeonTable
	questTable, err := decodeQuestTable(source)
	if err != nil {
		return nil, err
	}
	tables[questTableName] = questTable
	questRewardTable, err := decodeQuestRewardTable(source)
	if err != nil {
		return nil, err
	}
	tables[questRewardTableName] = questRewardTable
	levelExpTable, err := decodeLevelExpTable(source)
	if err != nil {
		return nil, err
	}
	tables[levelExpTableName] = levelExpTable
	achievementTable, err := decodeAchievementTable(source)
	if err != nil {
		return nil, err
	}
	tables[achievementTableName] = achievementTable
	vipLevelTable, err := decodeVipLevelTable(source)
	if err != nil {
		return nil, err
	}
	tables[vipLevelTableName] = vipLevelTable
	gameSettingsTable, err := decodeGameSettingsTable(source)
	if err != nil {
		return nil, err
	}
	tables[gameSettingsTableName] = gameSettingsTable
	maintenanceWindowTable, err := decodeMaintenanceWindowTable(source)
	if err != nil {
		return nil, err
	}
	tables[maintenanceWindowTableName] = maintenanceWindowTable
	mailTemplateTable, err := decodeMailTemplateTable(source)
	if err != nil {
		return nil, err
	}
	tables[mailTemplateTableName] = mailTemplateTable
	mailRewardTable, err := decodeMailRewardTable(source)
	if err != nil {
		return nil, err
	}
	tables[mailRewardTableName] = mailRewardTable
	dialogueTable, err := decodeDialogueTable(source)
	if err != nil {
		return nil, err
	}
	tables[dialogueTableName] = dialogueTable
	eventRuleTable, err := decodeEventRuleTable(source)
	if err != nil {
		return nil, err
	}
	tables[eventRuleTableName] = eventRuleTable
	complexRuleTable, err := decodeComplexRuleTable(source)
	if err != nil {
		return nil, err
	}
	tables[complexRuleTableName] = complexRuleTable
	complexConditionGroupTable, err := decodeComplexConditionGroupTable(source)
	if err != nil {
		return nil, err
	}
	tables[complexConditionGroupTableName] = complexConditionGroupTable
	complexConditionGroupEntryTable, err := decodeComplexConditionGroupEntryTable(source)
	if err != nil {
		return nil, err
	}
	tables[complexConditionGroupEntryTableName] = complexConditionGroupEntryTable
	complexRuleConditionTable, err := decodeComplexRuleConditionTable(source)
	if err != nil {
		return nil, err
	}
	tables[complexRuleConditionTableName] = complexRuleConditionTable
	complexActionGroupTable, err := decodeComplexActionGroupTable(source)
	if err != nil {
		return nil, err
	}
	tables[complexActionGroupTableName] = complexActionGroupTable
	complexActionEntryTable, err := decodeComplexActionEntryTable(source)
	if err != nil {
		return nil, err
	}
	tables[complexActionEntryTableName] = complexActionEntryTable
	return &SoraConfig{tables: tables}, nil
}

func (config *SoraConfig) Tables() []SoraTable {
	tables := make([]SoraTable, 0, len(config.tables))
	for _, table := range config.tables {
		tables = append(tables, table)
	}
	return tables
}

type SoraI18n struct {
	activeLocale string
	packs        map[string]*LocalePack
}

func NewSoraI18n() *SoraI18n {
	return &SoraI18n{
		activeLocale: "zh_cn",
		packs:        make(map[string]*LocalePack),
	}
}

func (i18n *SoraI18n) Mount(config *SoraConfig, pack *LocalePack) error {
	if pack.SchemaFingerprint() != SoraSchemaFingerprint {
		return fmt.Errorf("locale pack schema fingerprint mismatch: generated code expects %s, pack contains %s", SoraSchemaFingerprint, pack.SchemaFingerprint())
	}
	if !isDeclaredLocale(pack.Locale()) {
		return fmt.Errorf("locale pack `%s` is not declared by generated code", pack.Locale())
	}
	if err := config.validateLocalePack(pack); err != nil {
		return err
	}
	i18n.packs[pack.Locale()] = pack
	return nil
}

func (i18n *SoraI18n) SetLocale(locale string) error {
	if !isDeclaredLocale(locale) {
		return fmt.Errorf("unknown locale `%s`", locale)
	}
	if _, ok := i18n.packs[locale]; !ok {
		return fmt.Errorf("locale `%s` is not mounted", locale)
	}
	i18n.activeLocale = locale
	return nil
}

func (i18n *SoraI18n) Text(key TextKey) string {
	pack, ok := i18n.packs[i18n.activeLocale]
	if !ok {
		panic("active locale pack is not mounted or failed locale validation")
	}
	value, ok := pack.Get(key)
	if !ok {
		panic("active locale pack is not mounted or failed locale validation")
	}
	return value
}

func (i18n *SoraI18n) Format(key TextKey, args map[string]any) (string, error) {
	return FormatText(i18n.Text(key), args)
}

func isDeclaredLocale(locale string) bool {
	switch locale {
	case "zh_cn":
		return true
	case "en_us":
		return true
	default:
		return false
	}
}

func (config *SoraConfig) validateLocalePack(pack *LocalePack) error {
	for _, key := range config.textKeys() {
		value, ok := pack.Get(key)
		if !ok {
			return fmt.Errorf("text key `%s` is missing for locale `%s`", key.String(), pack.Locale())
		}
		if value == "" {
			return fmt.Errorf("text key `%s` has empty text for locale `%s`", key.String(), pack.Locale())
		}
	}
	return nil
}

func (config *SoraConfig) textKeys() []TextKey {
	keys := make([]TextKey, 0)
	for _, row := range config.Item().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.Shop().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.ShopItem().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.Recipe().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.GachaPool().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.GachaItem().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.EquipmentSet().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.Skill().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.Character().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.CharacterSkill().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.Buff().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.DropGroup().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.DropEntry().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.Monster().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.Stage().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.StageReward().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.Dungeon().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.Quest().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.QuestReward().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.LevelExp().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.Achievement().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.VipLevel().Rows() {
		row.collectTextKeys(&keys)
	}
	config.GameSettings().Row().collectTextKeys(&keys)
	for _, row := range config.MaintenanceWindow().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.MailTemplate().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.MailReward().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.Dialogue().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.EventRule().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.ComplexRule().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.ComplexConditionGroup().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.ComplexConditionGroupEntry().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.ComplexRuleCondition().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.ComplexActionGroup().Rows() {
		row.collectTextKeys(&keys)
	}
	for _, row := range config.ComplexActionEntry().Rows() {
		row.collectTextKeys(&keys)
	}
	return keys
}
func (config *SoraConfig) Item() *ItemTable {
	return config.tables[itemTableName].(*ItemTable)
}
func (config *SoraConfig) Shop() *ShopTable {
	return config.tables[shopTableName].(*ShopTable)
}
func (config *SoraConfig) ShopItem() *ShopItemTable {
	return config.tables[shopItemTableName].(*ShopItemTable)
}
func (config *SoraConfig) Recipe() *RecipeTable {
	return config.tables[recipeTableName].(*RecipeTable)
}
func (config *SoraConfig) GachaPool() *GachaPoolTable {
	return config.tables[gachaPoolTableName].(*GachaPoolTable)
}
func (config *SoraConfig) GachaItem() *GachaItemTable {
	return config.tables[gachaItemTableName].(*GachaItemTable)
}
func (config *SoraConfig) EquipmentSet() *EquipmentSetTable {
	return config.tables[equipmentSetTableName].(*EquipmentSetTable)
}
func (config *SoraConfig) Skill() *SkillTable {
	return config.tables[skillTableName].(*SkillTable)
}
func (config *SoraConfig) Character() *CharacterTable {
	return config.tables[characterTableName].(*CharacterTable)
}
func (config *SoraConfig) CharacterSkill() *CharacterSkillTable {
	return config.tables[characterSkillTableName].(*CharacterSkillTable)
}
func (config *SoraConfig) Buff() *BuffTable {
	return config.tables[buffTableName].(*BuffTable)
}
func (config *SoraConfig) DropGroup() *DropGroupTable {
	return config.tables[dropGroupTableName].(*DropGroupTable)
}
func (config *SoraConfig) DropEntry() *DropEntryTable {
	return config.tables[dropEntryTableName].(*DropEntryTable)
}
func (config *SoraConfig) Monster() *MonsterTable {
	return config.tables[monsterTableName].(*MonsterTable)
}
func (config *SoraConfig) Stage() *StageTable {
	return config.tables[stageTableName].(*StageTable)
}
func (config *SoraConfig) StageReward() *StageRewardTable {
	return config.tables[stageRewardTableName].(*StageRewardTable)
}
func (config *SoraConfig) Dungeon() *DungeonTable {
	return config.tables[dungeonTableName].(*DungeonTable)
}
func (config *SoraConfig) Quest() *QuestTable {
	return config.tables[questTableName].(*QuestTable)
}
func (config *SoraConfig) QuestReward() *QuestRewardTable {
	return config.tables[questRewardTableName].(*QuestRewardTable)
}
func (config *SoraConfig) LevelExp() *LevelExpTable {
	return config.tables[levelExpTableName].(*LevelExpTable)
}
func (config *SoraConfig) Achievement() *AchievementTable {
	return config.tables[achievementTableName].(*AchievementTable)
}
func (config *SoraConfig) VipLevel() *VipLevelTable {
	return config.tables[vipLevelTableName].(*VipLevelTable)
}
func (config *SoraConfig) GameSettings() *GameSettingsTable {
	return config.tables[gameSettingsTableName].(*GameSettingsTable)
}
func (config *SoraConfig) MaintenanceWindow() *MaintenanceWindowTable {
	return config.tables[maintenanceWindowTableName].(*MaintenanceWindowTable)
}
func (config *SoraConfig) MailTemplate() *MailTemplateTable {
	return config.tables[mailTemplateTableName].(*MailTemplateTable)
}
func (config *SoraConfig) MailReward() *MailRewardTable {
	return config.tables[mailRewardTableName].(*MailRewardTable)
}
func (config *SoraConfig) Dialogue() *DialogueTable {
	return config.tables[dialogueTableName].(*DialogueTable)
}
func (config *SoraConfig) EventRule() *EventRuleTable {
	return config.tables[eventRuleTableName].(*EventRuleTable)
}
func (config *SoraConfig) ComplexRule() *ComplexRuleTable {
	return config.tables[complexRuleTableName].(*ComplexRuleTable)
}
func (config *SoraConfig) ComplexConditionGroup() *ComplexConditionGroupTable {
	return config.tables[complexConditionGroupTableName].(*ComplexConditionGroupTable)
}
func (config *SoraConfig) ComplexConditionGroupEntry() *ComplexConditionGroupEntryTable {
	return config.tables[complexConditionGroupEntryTableName].(*ComplexConditionGroupEntryTable)
}
func (config *SoraConfig) ComplexRuleCondition() *ComplexRuleConditionTable {
	return config.tables[complexRuleConditionTableName].(*ComplexRuleConditionTable)
}
func (config *SoraConfig) ComplexActionGroup() *ComplexActionGroupTable {
	return config.tables[complexActionGroupTableName].(*ComplexActionGroupTable)
}
func (config *SoraConfig) ComplexActionEntry() *ComplexActionEntryTable {
	return config.tables[complexActionEntryTableName].(*ComplexActionEntryTable)
}
func DecodeMapTable[K comparable, V any](rows []V, key func(V) K) map[K]V {
	values := make(map[K]V, len(rows))
	for _, row := range rows {
		values[key(row)] = row
	}
	return values
}
func DecodeUniqueIndex[K comparable, V any](rows []V, key func(V) K) map[K]V {
	values := make(map[K]V, len(rows))
	for _, row := range rows {
		values[key(row)] = row
	}
	return values
}
func DecodeIndex[K comparable, V any](rows []V, key func(V) K) map[K][]V {
	values := make(map[K][]V)
	for _, row := range rows {
		indexKey := key(row)
		values[indexKey] = append(values[indexKey], row)
	}
	return values
}
func RequireSingletonTable[T any](rows []T, name string) (T, error) {
	var zero T
	if len(rows) != 1 {
		return zero, fmt.Errorf("expected singleton table `%s` to contain exactly 1 row, got %d", name, len(rows))
	}
	return rows[0], nil
}
