// This file was generated by Sora. Do not edit manually.

package showcase

type DropEntry struct {
    GroupId int32
    Seq int32
    ItemId int32
    Count int32
    Weight float32
}

func decodeDropEntry(reader *SoraReader) (DropEntry, error) {
    var value DropEntry
    var err error
    value.GroupId, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Seq, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.ItemId, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Count, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Weight, err = reader.ReadFloat32()
    if err != nil {
        return value, err
    }
    return value, nil
}
