// This file was generated by Sora. Do not edit manually.

package showcase

type DropEntry struct {
	GroupID int32
	Seq     int32
	ItemID  int32
	Count   int32
	Weight  float32
}

func decodeDropEntry(reader *SoraReader) (DropEntry, error) {
	var value DropEntry
	var err error
	value.GroupID, err = reader.ReadInt32()
	if err != nil {
		return value, err
	}
	value.Seq, err = reader.ReadInt32()
	if err != nil {
		return value, err
	}
	value.ItemID, err = reader.ReadInt32()
	if err != nil {
		return value, err
	}
	value.Count, err = reader.ReadInt32()
	if err != nil {
		return value, err
	}
	value.Weight, err = reader.ReadFloat32()
	if err != nil {
		return value, err
	}
	return value, nil
}

func decodeDropEntryValue(input SoraValue) (DropEntry, error) {
	var value DropEntry
	obj, err := input.AsObject()
	if err != nil {
		return value, err
	}
	value.GroupID, err = obj.Get("group_id").AsInt32()
	if err != nil {
		return value, err
	}
	value.Seq, err = obj.Get("seq").AsInt32()
	if err != nil {
		return value, err
	}
	value.ItemID, err = obj.Get("item_id").AsInt32()
	if err != nil {
		return value, err
	}
	value.Count, err = obj.Get("count").AsInt32()
	if err != nil {
		return value, err
	}
	value.Weight, err = obj.Get("weight").AsFloat32()
	if err != nil {
		return value, err
	}
	return value, nil
}

func (value DropEntry) collectTextKeys(out *[]TextKey) {
}

const dropEntryTableName = "DropEntry"

var dropEntryTableInfo = SoraTableInfo{
	Name:    dropEntryTableName,
	RowType: "DropEntry",
	Shape:   SoraTableShapeList,
	Indexes: []SoraIndexInfo{},
}

type DropEntryTable struct {
	rows []DropEntry
}

func buildDropEntryTable(rows []DropEntry) (*DropEntryTable, error) {
	return &DropEntryTable{rows: rows}, nil
}

func decodeDropEntryTable(source SoraTableSource) (*DropEntryTable, error) {
	rows, err := DecodeSourceTable(source, dropEntryTableName, decodeDropEntry, decodeDropEntryValue)
	if err != nil {
		return nil, err
	}
	return buildDropEntryTable(rows)
}
func (table *DropEntryTable) Rows() []DropEntry {
	return append([]DropEntry(nil), table.rows...)
}
func (table *DropEntryTable) Info() SoraTableInfo {
	return dropEntryTableInfo
}

func (table *DropEntryTable) Len() int {
	return len(table.rows)
}
