// This file was generated by Sora. Do not edit manually.

package showcase

type DropGroup struct {
	Id   int32
	Name string
}

func decodeDropGroup(reader *SoraReader) (DropGroup, error) {
	var value DropGroup
	var err error
	value.Id, err = reader.ReadInt32()
	if err != nil {
		return value, err
	}
	value.Name, err = reader.ReadString()
	if err != nil {
		return value, err
	}
	return value, nil
}

func decodeDropGroupValue(input SoraValue) (DropGroup, error) {
	var value DropGroup
	obj, err := input.AsObject()
	if err != nil {
		return value, err
	}
	value.Id, err = obj.Get("id").AsInt32()
	if err != nil {
		return value, err
	}
	value.Name, err = obj.Get("name").AsString()
	if err != nil {
		return value, err
	}
	return value, nil
}

const dropGroupTableName = "DropGroup"

type DropGroupTable struct {
	keys []int32
	rows map[int32]DropGroup
}

func buildDropGroupTable(rows []DropGroup) (*DropGroupTable, error) {
	keys := make([]int32, 0, len(rows))
	for _, row := range rows {
		keys = append(keys, row.Id)
	}
	return &DropGroupTable{keys: keys, rows: DecodeMapTable(rows, func(row DropGroup) int32 { return row.Id })}, nil
}

func decodeDropGroupTable(source SoraTableSource) (*DropGroupTable, error) {
	rows, err := DecodeSourceTable(source, dropGroupTableName, decodeDropGroup, decodeDropGroupValue)
	if err != nil {
		return nil, err
	}
	return buildDropGroupTable(rows)
}

func (table *DropGroupTable) Rows() map[int32]DropGroup {
	return table.rows
}
func (table *DropGroupTable) Get(key int32) (DropGroup, bool) {
	value, ok := table.rows[key]
	return value, ok
}

func (table *DropGroupTable) Keys() []int32 {
	return table.keys
}

func (table *DropGroupTable) OrderedRows() []DropGroup {
	rows := make([]DropGroup, 0, len(table.keys))
	for _, key := range table.keys {
		if row, ok := table.rows[key]; ok {
			rows = append(rows, row)
		}
	}
	return rows
}
func (table *DropGroupTable) Name() string {
	return dropGroupTableName
}

func (table *DropGroupTable) Mode() SoraTableMode {
	return SoraTableModeMap
}

func (table *DropGroupTable) Key() string {
	return "id"
}

func (table *DropGroupTable) RowType() string {
	return "DropGroup"
}

func (table *DropGroupTable) Len() int {
	return len(table.rows)
}
