// This file was generated by Sora. Do not edit manually.

package showcase

import "fmt"

type ElementType int32

const (
    ElementTypeFire ElementType = 0
    ElementTypeIce ElementType = 1
    ElementTypeLightning ElementType = 2
    ElementTypePhysical ElementType = 3
)

func decodeElementType(reader *SoraReader) (ElementType, error) {
    ordinal, err := reader.ReadUInt32()
    if err != nil {
        return 0, err
    }
    switch ordinal {
    case 0:
        return ElementTypeFire, nil
    case 1:
        return ElementTypeIce, nil
    case 2:
        return ElementTypeLightning, nil
    case 3:
        return ElementTypePhysical, nil
    default:
        return 0, fmt.Errorf("invalid enum ordinal %d for ElementType", ordinal)
    }
}
