// This file was generated by Sora. Do not edit manually.

package showcase

import "fmt"

type EventCondition interface {
	isEventCondition()
}
type EventConditionLevelAtLeast struct {
	Level int32
}

func (EventConditionLevelAtLeast) isEventCondition() {}

type EventConditionQuestCompleted struct {
	QuestId int32
}

func (EventConditionQuestCompleted) isEventCondition() {}

type EventConditionHasItem struct {
	ItemId int32
	Count  int32
}

func (EventConditionHasItem) isEventCondition() {}

type EventConditionAllConditions struct {
	ConditionGroupId int32
}

func (EventConditionAllConditions) isEventCondition() {}

type EventConditionAnyCondition struct {
	ConditionGroupId int32
}

func (EventConditionAnyCondition) isEventCondition() {}
func decodeEventCondition(reader *SoraReader) (EventCondition, error) {
	ordinal, err := reader.ReadUInt32()
	if err != nil {
		return nil, err
	}
	switch ordinal {
	case 0:
		var value EventConditionLevelAtLeast
		value.Level, err = reader.ReadInt32()
		if err != nil {
			return nil, err
		}
		return value, nil
	case 1:
		var value EventConditionQuestCompleted
		value.QuestId, err = reader.ReadInt32()
		if err != nil {
			return nil, err
		}
		return value, nil
	case 2:
		var value EventConditionHasItem
		value.ItemId, err = reader.ReadInt32()
		if err != nil {
			return nil, err
		}
		value.Count, err = reader.ReadInt32()
		if err != nil {
			return nil, err
		}
		return value, nil
	case 3:
		var value EventConditionAllConditions
		value.ConditionGroupId, err = reader.ReadInt32()
		if err != nil {
			return nil, err
		}
		return value, nil
	case 4:
		var value EventConditionAnyCondition
		value.ConditionGroupId, err = reader.ReadInt32()
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, fmt.Errorf("invalid union ordinal %d for EventCondition", ordinal)
	}
}

func decodeEventConditionValue(input SoraValue) (EventCondition, error) {
	obj, err := input.AsObject()
	if err != nil {
		return nil, err
	}
	tag, err := obj.Get("type").AsString()
	if err != nil {
		return nil, err
	}
	switch tag {
	case "LevelAtLeast":
		var value EventConditionLevelAtLeast
		value.Level, err = obj.Get("level").AsInt32()
		if err != nil {
			return nil, err
		}
		return value, nil
	case "QuestCompleted":
		var value EventConditionQuestCompleted
		value.QuestId, err = obj.Get("quest_id").AsInt32()
		if err != nil {
			return nil, err
		}
		return value, nil
	case "HasItem":
		var value EventConditionHasItem
		value.ItemId, err = obj.Get("item_id").AsInt32()
		if err != nil {
			return nil, err
		}
		value.Count, err = obj.Get("count").AsInt32()
		if err != nil {
			return nil, err
		}
		return value, nil
	case "AllConditions":
		var value EventConditionAllConditions
		value.ConditionGroupId, err = obj.Get("condition_group_id").AsInt32()
		if err != nil {
			return nil, err
		}
		return value, nil
	case "AnyCondition":
		var value EventConditionAnyCondition
		value.ConditionGroupId, err = obj.Get("condition_group_id").AsInt32()
		if err != nil {
			return nil, err
		}
		return value, nil
	default:
		return nil, fmt.Errorf("invalid union tag %s for EventCondition", tag)
	}
}
