// This file was generated by Sora. Do not edit manually.

package showcase

type EventRule struct {
    Id int32
    Name string
    Condition EventCondition
    Actions []RewardAction
}

func decodeEventRule(reader *SoraReader) (EventRule, error) {
    var value EventRule
    var err error
    value.Id, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Name, err = reader.ReadString()
    if err != nil {
        return value, err
    }
    value.Condition, err = decodeEventCondition(reader)
    if err != nil {
        return value, err
    }
    value.Actions, err = ReadList(reader, func(reader *SoraReader) (RewardAction, error) { return decodeRewardAction(reader) })
    if err != nil {
        return value, err
    }
    return value, nil
}

func decodeEventRuleValue(input SoraValue) (EventRule, error) {
    var value EventRule
    obj, err := input.AsObject()
    if err != nil {
        return value, err
    }
    value.Id, err = obj.Get("id").AsInt32()
    if err != nil {
        return value, err
    }
    value.Name, err = obj.Get("name").AsString()
    if err != nil {
        return value, err
    }
    value.Condition, err = decodeEventConditionValue(obj.Get("condition"))
    if err != nil {
        return value, err
    }
    value.Actions, err = DecodeSoraValueList(obj.Get("actions"), func(item SoraValue) (RewardAction, error) { return decodeRewardActionValue(item) })
    if err != nil {
        return value, err
    }
    return value, nil
}

const eventRuleTableName = "EventRule"

var eventRuleTableInfo = SoraTableInfo{
    Name: eventRuleTableName,
    RowType: "EventRule",
    Shape: SoraTableShapeKeyed,
    PrimaryKey: &SoraKeyInfo{Name: "id", Type: "int32"},
    Indexes: []SoraIndexInfo{
    },
}

type EventRuleTable struct {
    keys []int32
    rows map[int32]EventRule
}

func buildEventRuleTable(rows []EventRule) (*EventRuleTable, error) {
    keys := make([]int32, 0, len(rows))
    for _, row := range rows {
        keys = append(keys, row.Id)
    }
    return &EventRuleTable{keys: keys, rows: DecodeMapTable(rows, func(row EventRule) int32 { return row.Id })}, nil
}

func decodeEventRuleTable(source SoraTableSource) (*EventRuleTable, error) {
    rows, err := DecodeSourceTable(source, eventRuleTableName, decodeEventRule, decodeEventRuleValue)
    if err != nil {
        return nil, err
    }
    return buildEventRuleTable(rows)
}

func (table *EventRuleTable) Rows() map[int32]EventRule {
    return table.rows
}
func (table *EventRuleTable) Get(key int32) (EventRule, bool) {
    value, ok := table.rows[key]
    return value, ok
}

func (table *EventRuleTable) Keys() []int32 {
    return table.keys
}

func (table *EventRuleTable) OrderedRows() []EventRule {
    rows := make([]EventRule, 0, len(table.keys))
    for _, key := range table.keys {
        if row, ok := table.rows[key]; ok {
            rows = append(rows, row)
        }
    }
    return rows
}
func (table *EventRuleTable) Info() SoraTableInfo {
    return eventRuleTableInfo
}

func (table *EventRuleTable) Len() int {
    return len(table.rows)
}
