// This file was generated by Sora. Do not edit manually.

package showcase

type GachaItem struct {
    PoolId int32
    ItemId int32
    Rarity Rarity
    Weight float32
}

func decodeGachaItem(reader *SoraReader) (GachaItem, error) {
    var value GachaItem
    var err error
    value.PoolId, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.ItemId, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Rarity, err = decodeRarity(reader)
    if err != nil {
        return value, err
    }
    value.Weight, err = reader.ReadFloat32()
    if err != nil {
        return value, err
    }
    return value, nil
}

type GachaItemTable struct {
    rows []GachaItem
}

func buildGachaItemTable(rows []GachaItem) (*GachaItemTable, error) {
    return &GachaItemTable{rows: rows}, nil
}

func decodeGachaItemTable(bundle *SoraBundle) (*GachaItemTable, error) {
    rows, err := DecodeTable(bundle, "GachaItem", decodeGachaItem)
    if err != nil {
        return nil, err
    }
    return buildGachaItemTable(rows)
}

func (table *GachaItemTable) Rows() []GachaItem {
    return table.rows
}
func (table *GachaItemTable) Name() string {
    return "GachaItem"
}

func (table *GachaItemTable) Mode() SoraTableMode {
    return SoraTableModeList
}

func (table *GachaItemTable) Key() string {
    return ""
}

func (table *GachaItemTable) RowType() string {
    return "GachaItem"
}

func (table *GachaItemTable) Len() int {
    return len(table.rows)
}
