// This file was generated by Sora. Do not edit manually.

package showcase

type GachaPool struct {
	Id   int32
	Name string
	Cost ResourceCost
}

func decodeGachaPool(reader *SoraReader) (GachaPool, error) {
	var value GachaPool
	var err error
	value.Id, err = reader.ReadInt32()
	if err != nil {
		return value, err
	}
	value.Name, err = reader.ReadString()
	if err != nil {
		return value, err
	}
	value.Cost, err = decodeResourceCost(reader)
	if err != nil {
		return value, err
	}
	return value, nil
}

func decodeGachaPoolValue(input SoraValue) (GachaPool, error) {
	var value GachaPool
	obj, err := input.AsObject()
	if err != nil {
		return value, err
	}
	value.Id, err = obj.Get("id").AsInt32()
	if err != nil {
		return value, err
	}
	value.Name, err = obj.Get("name").AsString()
	if err != nil {
		return value, err
	}
	value.Cost, err = decodeResourceCostValue(obj.Get("cost"))
	if err != nil {
		return value, err
	}
	return value, nil
}

const gachaPoolTableName = "GachaPool"

type GachaPoolTable struct {
	keys []int32
	rows map[int32]GachaPool
}

func buildGachaPoolTable(rows []GachaPool) (*GachaPoolTable, error) {
	keys := make([]int32, 0, len(rows))
	for _, row := range rows {
		keys = append(keys, row.Id)
	}
	return &GachaPoolTable{keys: keys, rows: DecodeMapTable(rows, func(row GachaPool) int32 { return row.Id })}, nil
}

func decodeGachaPoolTable(source SoraTableSource) (*GachaPoolTable, error) {
	rows, err := DecodeSourceTable(source, gachaPoolTableName, decodeGachaPool, decodeGachaPoolValue)
	if err != nil {
		return nil, err
	}
	return buildGachaPoolTable(rows)
}

func (table *GachaPoolTable) Rows() map[int32]GachaPool {
	return table.rows
}
func (table *GachaPoolTable) Get(key int32) (GachaPool, bool) {
	value, ok := table.rows[key]
	return value, ok
}

func (table *GachaPoolTable) Keys() []int32 {
	return table.keys
}

func (table *GachaPoolTable) OrderedRows() []GachaPool {
	rows := make([]GachaPool, 0, len(table.keys))
	for _, key := range table.keys {
		if row, ok := table.rows[key]; ok {
			rows = append(rows, row)
		}
	}
	return rows
}
func (table *GachaPoolTable) Name() string {
	return gachaPoolTableName
}

func (table *GachaPoolTable) Mode() SoraTableMode {
	return SoraTableModeMap
}

func (table *GachaPoolTable) Key() string {
	return "id"
}

func (table *GachaPoolTable) Len() int {
	return len(table.rows)
}
