// This file was generated by Sora. Do not edit manually.

package showcase

type GameSettings struct {
    Version string
    DailyResetHour int32
    StartingGold int32
    SpawnPos Vec3
    StarterItems []int32
}

func decodeGameSettings(reader *SoraReader) (GameSettings, error) {
    var value GameSettings
    var err error
    value.Version, err = reader.ReadString()
    if err != nil {
        return value, err
    }
    value.DailyResetHour, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.StartingGold, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.SpawnPos, err = decodeVec3(reader)
    if err != nil {
        return value, err
    }
    value.StarterItems, err = ReadList(reader, func(reader *SoraReader) (int32, error) { return reader.ReadInt32() })
    if err != nil {
        return value, err
    }
    return value, nil
}

type GameSettingsTable struct {
    rows GameSettings
}

func buildGameSettingsTable(rows []GameSettings) (*GameSettingsTable, error) {
    row, err := RequireSingletonTable(rows, "GameSettings")
    if err != nil {
        return nil, err
    }
    return &GameSettingsTable{rows: row}, nil
}

func decodeGameSettingsTable(bundle *SoraBundle) (*GameSettingsTable, error) {
    rows, err := DecodeTable(bundle, "GameSettings", decodeGameSettings)
    if err != nil {
        return nil, err
    }
    return buildGameSettingsTable(rows)
}

func (table *GameSettingsTable) Rows() GameSettings {
    return table.rows
}
func (table *GameSettingsTable) Name() string {
    return "GameSettings"
}

func (table *GameSettingsTable) Mode() SoraTableMode {
    return SoraTableModeSingleton
}

func (table *GameSettingsTable) Key() string {
    return ""
}

func (table *GameSettingsTable) RowType() string {
    return "GameSettings"
}

func (table *GameSettingsTable) Len() int {
    return 1
}
