// This file was generated by Sora. Do not edit manually.

package showcase

import "fmt"

type ItemType int32

const (
    ItemTypeWeapon ItemType = 0
    ItemTypeArmor ItemType = 1
    ItemTypeCurrency ItemType = 2
    ItemTypeMaterial ItemType = 3
    ItemTypeConsumable ItemType = 4
)

func decodeItemType(reader *SoraReader) (ItemType, error) {
    ordinal, err := reader.ReadUInt32()
    if err != nil {
        return 0, err
    }
    switch ordinal {
    case 0:
        return ItemTypeWeapon, nil
    case 1:
        return ItemTypeArmor, nil
    case 2:
        return ItemTypeCurrency, nil
    case 3:
        return ItemTypeMaterial, nil
    case 4:
        return ItemTypeConsumable, nil
    default:
        return 0, fmt.Errorf("invalid enum ordinal %d for ItemType", ordinal)
    }
}
