// This file was generated by Sora. Do not edit manually.

package showcase

type LevelExp struct {
    Level int32
    Exp int64
    UnlockFeature *string
}

func decodeLevelExp(reader *SoraReader) (LevelExp, error) {
    var value LevelExp
    var err error
    value.Level, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Exp, err = reader.ReadInt64()
    if err != nil {
        return value, err
    }
    value.UnlockFeature, err = ReadOptional(reader, func(reader *SoraReader) (string, error) { return reader.ReadString() })
    if err != nil {
        return value, err
    }
    return value, nil
}

type LevelExpTable struct {
    rows map[int32]LevelExp
}

func buildLevelExpTable(rows []LevelExp) (*LevelExpTable, error) {
    return &LevelExpTable{rows: DecodeMapTable(rows, func(row LevelExp) int32 { return row.Level })}, nil
}

func decodeLevelExpTable(bundle *SoraBundle) (*LevelExpTable, error) {
    rows, err := DecodeTable(bundle, "LevelExp", decodeLevelExp)
    if err != nil {
        return nil, err
    }
    return buildLevelExpTable(rows)
}

func (table *LevelExpTable) Rows() map[int32]LevelExp {
    return table.rows
}
func (table *LevelExpTable) Get(key int32) (LevelExp, bool) {
    value, ok := table.rows[key]
    return value, ok
}
func (table *LevelExpTable) Name() string {
    return "LevelExp"
}

func (table *LevelExpTable) Mode() SoraTableMode {
    return SoraTableModeMap
}

func (table *LevelExpTable) Key() string {
    return "level"
}

func (table *LevelExpTable) RowType() string {
    return "LevelExp"
}

func (table *LevelExpTable) Len() int {
    return len(table.rows)
}
