// This file was generated by Sora. Do not edit manually.

package showcase

type MailTemplate struct {
    Id int32
    MailType MailType
    TitleKey string
    BodyKey string
    Rewards []Reward
}

func decodeMailTemplate(reader *SoraReader) (MailTemplate, error) {
    var value MailTemplate
    var err error
    value.Id, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.MailType, err = decodeMailType(reader)
    if err != nil {
        return value, err
    }
    value.TitleKey, err = reader.ReadString()
    if err != nil {
        return value, err
    }
    value.BodyKey, err = reader.ReadString()
    if err != nil {
        return value, err
    }
    value.Rewards, err = ReadList(reader, func(reader *SoraReader) (Reward, error) { return decodeReward(reader) })
    if err != nil {
        return value, err
    }
    return value, nil
}

type MailTemplateTable struct {
    rows map[int32]MailTemplate
}

func buildMailTemplateTable(rows []MailTemplate) (*MailTemplateTable, error) {
    return &MailTemplateTable{rows: DecodeMapTable(rows, func(row MailTemplate) int32 { return row.Id })}, nil
}

func decodeMailTemplateTable(bundle *SoraBundle) (*MailTemplateTable, error) {
    rows, err := DecodeTable(bundle, "MailTemplate", decodeMailTemplate)
    if err != nil {
        return nil, err
    }
    return buildMailTemplateTable(rows)
}

func (table *MailTemplateTable) Rows() map[int32]MailTemplate {
    return table.rows
}
func (table *MailTemplateTable) Get(key int32) (MailTemplate, bool) {
    value, ok := table.rows[key]
    return value, ok
}
func (table *MailTemplateTable) Name() string {
    return "MailTemplate"
}

func (table *MailTemplateTable) Mode() SoraTableMode {
    return SoraTableModeMap
}

func (table *MailTemplateTable) Key() string {
    return "id"
}

func (table *MailTemplateTable) RowType() string {
    return "MailTemplate"
}

func (table *MailTemplateTable) Len() int {
    return len(table.rows)
}
