// This file was generated by Sora. Do not edit manually.

package showcase

type QuestReward struct {
	QuestId int32
	Seq     int32
	ItemId  int32
	Count   int32
}

func decodeQuestReward(reader *SoraReader) (QuestReward, error) {
	var value QuestReward
	var err error
	value.QuestId, err = reader.ReadInt32()
	if err != nil {
		return value, err
	}
	value.Seq, err = reader.ReadInt32()
	if err != nil {
		return value, err
	}
	value.ItemId, err = reader.ReadInt32()
	if err != nil {
		return value, err
	}
	value.Count, err = reader.ReadInt32()
	if err != nil {
		return value, err
	}
	return value, nil
}

func decodeQuestRewardValue(input SoraValue) (QuestReward, error) {
	var value QuestReward
	obj, err := input.AsObject()
	if err != nil {
		return value, err
	}
	value.QuestId, err = obj.Get("quest_id").AsInt32()
	if err != nil {
		return value, err
	}
	value.Seq, err = obj.Get("seq").AsInt32()
	if err != nil {
		return value, err
	}
	value.ItemId, err = obj.Get("item_id").AsInt32()
	if err != nil {
		return value, err
	}
	value.Count, err = obj.Get("count").AsInt32()
	if err != nil {
		return value, err
	}
	return value, nil
}

func (value QuestReward) collectTextKeys(out *[]TextKey) {
}

const questRewardTableName = "QuestReward"

var questRewardTableInfo = SoraTableInfo{
	Name:    questRewardTableName,
	RowType: "QuestReward",
	Shape:   SoraTableShapeList,
	Indexes: []SoraIndexInfo{},
}

type QuestRewardTable struct {
	rows []QuestReward
}

func buildQuestRewardTable(rows []QuestReward) (*QuestRewardTable, error) {
	return &QuestRewardTable{rows: rows}, nil
}

func decodeQuestRewardTable(source SoraTableSource) (*QuestRewardTable, error) {
	rows, err := DecodeSourceTable(source, questRewardTableName, decodeQuestReward, decodeQuestRewardValue)
	if err != nil {
		return nil, err
	}
	return buildQuestRewardTable(rows)
}

func (table *QuestRewardTable) Rows() []QuestReward {
	return table.rows
}
func (table *QuestRewardTable) Info() SoraTableInfo {
	return questRewardTableInfo
}

func (table *QuestRewardTable) Len() int {
	return len(table.rows)
}
