// This file was generated by Sora. Do not edit manually.

package showcase

type Quest struct {
    Id int32
    QuestType QuestType
    Title string
    RequiredItem int32
    UnlockSkills []int32
    StartPos Vec3
    // Rewards: Materialized from QuestReward child rows
    Rewards []Reward
}

func decodeQuest(reader *SoraReader) (Quest, error) {
    var value Quest
    var err error
    value.Id, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.QuestType, err = decodeQuestType(reader)
    if err != nil {
        return value, err
    }
    value.Title, err = reader.ReadString()
    if err != nil {
        return value, err
    }
    value.RequiredItem, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.UnlockSkills, err = ReadList(reader, func(reader *SoraReader) (int32, error) { return reader.ReadInt32() })
    if err != nil {
        return value, err
    }
    value.StartPos, err = decodeVec3(reader)
    if err != nil {
        return value, err
    }
    value.Rewards, err = ReadList(reader, func(reader *SoraReader) (Reward, error) { return decodeReward(reader) })
    if err != nil {
        return value, err
    }
    return value, nil
}

type QuestTable struct {
    rows map[int32]Quest
}

func buildQuestTable(rows []Quest) (*QuestTable, error) {
    return &QuestTable{rows: DecodeMapTable(rows, func(row Quest) int32 { return row.Id })}, nil
}

func decodeQuestTable(bundle *SoraBundle) (*QuestTable, error) {
    rows, err := DecodeTable(bundle, "Quest", decodeQuest)
    if err != nil {
        return nil, err
    }
    return buildQuestTable(rows)
}

func (table *QuestTable) Rows() map[int32]Quest {
    return table.rows
}
func (table *QuestTable) Get(key int32) (Quest, bool) {
    value, ok := table.rows[key]
    return value, ok
}
func (table *QuestTable) Name() string {
    return "Quest"
}

func (table *QuestTable) Mode() SoraTableMode {
    return SoraTableModeMap
}

func (table *QuestTable) Key() string {
    return "id"
}

func (table *QuestTable) RowType() string {
    return "Quest"
}

func (table *QuestTable) Len() int {
    return len(table.rows)
}
