// This file was generated by Sora. Do not edit manually.

package showcase

type RewardBundle struct {
    Cost ResourceCost
    Weight int32
    Labels []string
}

func decodeRewardBundle(reader *SoraReader) (RewardBundle, error) {
    var value RewardBundle
    var err error
    value.Cost, err = decodeResourceCost(reader)
    if err != nil {
        return value, err
    }
    value.Weight, err = reader.ReadInt32()
    if err != nil {
        return value, err
    }
    value.Labels, err = ReadList(reader, func(reader *SoraReader) (string, error) { return reader.ReadString() })
    if err != nil {
        return value, err
    }
    return value, nil
}

func decodeRewardBundleValue(input SoraValue) (RewardBundle, error) {
    var value RewardBundle
    obj, err := input.AsObject()
    if err != nil {
        return value, err
    }
    value.Cost, err = decodeResourceCostValue(obj.Get("cost"))
    if err != nil {
        return value, err
    }
    value.Weight, err = obj.Get("weight").AsInt32()
    if err != nil {
        return value, err
    }
    value.Labels, err = DecodeSoraValueList(obj.Get("labels"), func(item SoraValue) (string, error) { return item.AsString() })
    if err != nil {
        return value, err
    }
    return value, nil
}
