// This file was generated by Sora. Do not edit manually.

package showcase

type StatModifier struct {
	Stat      StatType
	Value     float32
	IsPercent bool
}

func decodeStatModifier(reader *SoraReader) (StatModifier, error) {
	var value StatModifier
	var err error
	value.Stat, err = decodeStatType(reader)
	if err != nil {
		return value, err
	}
	value.Value, err = reader.ReadFloat32()
	if err != nil {
		return value, err
	}
	value.IsPercent, err = reader.ReadBool()
	if err != nil {
		return value, err
	}
	return value, nil
}

func decodeStatModifierValue(input SoraValue) (StatModifier, error) {
	var value StatModifier
	obj, err := input.AsObject()
	if err != nil {
		return value, err
	}
	value.Stat, err = decodeStatTypeValue(obj.Get("stat"))
	if err != nil {
		return value, err
	}
	value.Value, err = obj.Get("value").AsFloat32()
	if err != nil {
		return value, err
	}
	value.IsPercent, err = obj.Get("is_percent").AsBool()
	if err != nil {
		return value, err
	}
	return value, nil
}
