use super::*;
use crate::{
    csharp::CSharpCodeGenerator, go::GoCodeGenerator, java::JavaCodeGenerator,
    rust::RustCodeGenerator,
};
use sora_ir::{
    model::{ConfigIr, RuntimeFormatIr},
    normalize::normalize_schema,
};
use sora_schema::model::SchemaFile;
use std::{
    path::PathBuf,
    sync::atomic::{AtomicU64, Ordering},
};

static TEMP_COUNTER: AtomicU64 = AtomicU64::new(0);

#[test]
fn generates_rust_and_kotlin_files() {
    let ir = example_ir();
    let base = temp_dir();
    let rust_out = base.join("rust");
    let kotlin_out = base.join("kotlin");
    let kotlin_package_out = kotlin_out.join("game_config");

    RustCodeGenerator.generate(&ir, &rust_out).unwrap();
    KotlinCodeGenerator.generate(&ir, &kotlin_out).unwrap();

    let rust_item = std::fs::read_to_string(rust_out.join("item.rs")).unwrap();
    let rust_item_type = std::fs::read_to_string(rust_out.join("item_type.rs")).unwrap();
    let rust_action = std::fs::read_to_string(rust_out.join("action.rs")).unwrap();
    let rust_runtime = std::fs::read_to_string(rust_out.join("runtime.rs")).unwrap();
    let rust_mod = std::fs::read_to_string(rust_out.join("mod.rs")).unwrap();
    let kotlin_item = std::fs::read_to_string(kotlin_package_out.join("Item.kt")).unwrap();
    let kotlin_action = std::fs::read_to_string(kotlin_package_out.join("Action.kt")).unwrap();
    let kotlin_runtime = std::fs::read_to_string(kotlin_package_out.join("Runtime.kt")).unwrap();
    let kotlin_config = std::fs::read_to_string(kotlin_package_out.join("SoraConfig.kt")).unwrap();

    assert!(rust_item.starts_with("// This file was generated by Sora. Do not edit manually."));
    assert!(rust_item.contains("pub struct Item"));
    assert!(rust_item.contains("/// Item id"));
    assert!(rust_item.contains("pub item_type: ItemType"));
    assert!(rust_item.contains("pub action: Action"));
    assert!(rust_item.contains("impl super::runtime::SoraDecode for Item"));
    assert!(!rust_item.contains("impl std::fmt::Display for Item"));
    assert!(!rust_item_type.contains("impl std::fmt::Display for ItemType"));
    assert!(rust_action.contains("pub enum Action"));
    assert!(rust_action.contains("AddItem {"));
    assert!(rust_action.contains("impl super::runtime::SoraDecode for Action"));
    assert!(!rust_action.contains("impl std::fmt::Display for Action"));
    assert!(rust_runtime.contains("pub struct SoraBundle"));
    assert!(rust_runtime.contains("pub trait SoraTableSource"));
    assert!(rust_mod.contains("pub struct SoraConfig"));
    assert!(rust_mod.contains("from_source"));
    assert!(!rust_mod.contains("from_bytes"));
    assert!(rust_mod.contains("pub type SoraMap<K, V> = std::collections::HashMap<K, V>;"));
    assert!(rust_mod.contains("pub trait SoraTable: std::any::Any + Send + Sync"));
    assert!(rust_mod.contains("tables: SoraMap<&'static str, Box<dyn SoraTable>>"));
    assert!(rust_mod.contains("pub fn tables(&self) -> impl Iterator<Item = &dyn SoraTable>"));
    assert!(rust_mod.contains("source.decode_table::<item::Item>(\"Item\")?"));
    assert!(rust_item.contains("pub struct ItemTable"));
    assert!(rust_item.contains("rows: SoraMap<i32, Item>"));
    assert!(rust_item.contains("keys: Vec<i32>"));
    assert_contains_before(&rust_item, "keys: Vec<i32>", "rows: SoraMap<i32, Item>");
    assert!(rust_item.contains("by_name: SoraMap<String, i32>"));
    assert!(rust_item.contains("by_item_type: SoraMap<ItemType, Vec<i32>>"));
    assert!(rust_item.contains("impl super::SoraTable for ItemTable"));
    assert!(rust_item.contains("fn key(&self) -> Option<&'static str>"));
    assert!(rust_item.contains("Some(\"id\")"));
    assert!(rust_item.contains("impl std::ops::Deref for ItemTable"));
    assert!(rust_item.contains("|row| row.id"));
    assert!(rust_item.contains("|row| row.name.clone()"));
    assert!(rust_item.contains("|row| row.item_type"));
    assert!(rust_mod.contains("fn table<T: SoraTable + 'static>(&self, name: &'static str) -> &T"));
    assert!(!rust_mod.contains("as_any"));
    assert!(rust_mod.contains("let table: &dyn std::any::Any = table.as_ref();"));
    assert!(rust_mod.contains("table.downcast_ref::<T>()"));
    assert!(rust_mod.contains("pub fn item(&self) -> &item::ItemTable"));
    assert!(rust_item.contains("pub fn get(&self, key: i32) -> Option<&Item>"));
    assert!(rust_item.contains("pub fn keys(&self) -> &[i32]"));
    assert!(rust_item.contains("pub fn ordered_rows(&self) -> impl Iterator<Item = &Item>"));
    assert!(rust_item.contains("pub fn get_by_name(&self, name: &str) -> Option<&Item>"));
    assert!(rust_item.contains(
        "pub fn find_by_item_type(&self, item_type: ItemType) -> impl Iterator<Item = &Item>"
    ));
    assert!(!rust_mod.contains("pub fn get_item"));
    assert!(!rust_mod.contains("pub fn iter_item"));
    assert!(!rust_mod.contains("decode_singleton_table"));
    assert!(kotlin_item.starts_with("// This file was generated by Sora. Do not edit manually."));
    assert!(kotlin_item.contains("data class Item"));
    assert!(kotlin_item.contains("package game_config"));
    assert!(kotlin_item.contains("/** Item id */"));
    assert!(kotlin_item.contains("val itemType: ItemType"));
    assert!(kotlin_item.contains("val action: Action"));
    assert!(kotlin_action.contains("sealed class Action"));
    assert!(kotlin_action.contains("data class AddItem"));
    assert!(kotlin_action.contains("fun decode(reader: SoraReader): Action"));
    assert!(kotlin_item.contains("fun decode(reader: SoraReader): Item"));
    assert!(kotlin_item.contains("fun decode(value: SoraValue): Item"));
    assert!(kotlin_runtime.contains("class SoraBundle"));
    assert!(kotlin_runtime.contains("interface SoraTableSource"));
    assert!(kotlin_config.contains("interface SoraTable"));
    assert!(kotlin_config.contains("class SoraConfig private constructor"));
    assert!(kotlin_config.contains("private val tableMap: Map<String, SoraTable>"));
    assert!(kotlin_config.contains("val item: ItemTable"));
    assert!(kotlin_config.contains("get() = table(\"Item\")"));
    assert!(kotlin_config.contains("fun fromSource(source: SoraTableSource): SoraConfig"));
    assert!(!kotlin_config.contains("fromBytes"));
    assert!(kotlin_config.contains("tables[\"Item\"] = ItemTable.decode(source)"));
    assert!(kotlin_item.contains("class ItemTable private constructor"));
    assert!(kotlin_item.contains("val rows: Map<Int, Item>"));
    assert!(kotlin_item.contains("val orderedKeys: List<Int>"));
    assert!(kotlin_item.contains(") : SoraTable, Map<Int, Item> by rows"));
    assert_contains_before(
        &kotlin_item,
        "val orderedKeys: List<Int>",
        "val rows: Map<Int, Item>",
    );
    assert!(kotlin_item.contains("private val nameIndex: Map<String, Item>"));
    assert!(kotlin_item.contains("private val itemTypeIndex: Map<ItemType, List<Item>>"));
    assert!(
        kotlin_item
            .contains("fun orderedValues(): List<Item> = orderedKeys.mapNotNull { rows[it] }")
    );
    assert!(kotlin_item.contains("fun getByName(name: String): Item? = nameIndex[name]"));
    assert!(kotlin_item.contains(
        "fun findByItemType(itemType: ItemType): List<Item> = itemTypeIndex[itemType].orEmpty()"
    ));

    let _ = std::fs::remove_dir_all(base);
}

#[test]
fn kotlin_files_are_written_under_package_path() {
    let mut ir = example_ir();
    ir.package = "com.sora.game_config".to_owned();
    let base = temp_dir();
    let kotlin_out = base.join("kotlin");

    KotlinCodeGenerator.generate(&ir, &kotlin_out).unwrap();

    let item = std::fs::read_to_string(kotlin_out.join("com/sora/game_config/Item.kt")).unwrap();
    assert!(item.contains("package com.sora.game_config"));
    assert!(!kotlin_out.join("Item.kt").exists());

    let _ = std::fs::remove_dir_all(base);
}

#[test]
fn kotlin_package_path_rejects_invalid_segments() {
    let mut ir = example_ir();
    ir.package = "com.sora-game".to_owned();
    let base = temp_dir();

    let error = KotlinCodeGenerator
        .generate(&ir, &base.join("kotlin"))
        .unwrap_err();

    assert!(
        error
            .to_string()
            .contains("dot-separated identifier segments")
    );

    let _ = std::fs::remove_dir_all(base);
}

#[test]
fn rust_config_api_respects_table_modes() {
    let ir = table_mode_ir();
    let base = temp_dir();
    let rust_out = base.join("rust");

    RustCodeGenerator.generate(&ir, &rust_out).unwrap();

    let rust_mod = std::fs::read_to_string(rust_out.join("mod.rs")).unwrap();
    let rust_item = std::fs::read_to_string(rust_out.join("item.rs")).unwrap();
    let rust_settings = std::fs::read_to_string(rust_out.join("settings.rs")).unwrap();
    assert!(rust_item.contains("pub struct ItemTable"));
    assert!(rust_item.contains("rows: SoraMap<i32, Item>"));
    assert!(rust_settings.contains("pub struct SettingsTable"));
    assert!(rust_settings.contains("rows: Settings"));
    assert!(rust_mod.contains("pub fn item(&self) -> &item::ItemTable"));
    assert!(rust_mod.contains("pub fn settings(&self) -> &settings::SettingsTable"));
    assert!(!rust_mod.contains("pub fn settings_row"));
    assert!(rust_mod.contains("decode_singleton_table"));

    let _ = std::fs::remove_dir_all(base);
}

#[test]
fn kotlin_list_tables_extend_abstract_list() {
    let ir = table_mode_ir();
    let base = temp_dir();
    let kotlin_out = base.join("kotlin");

    KotlinCodeGenerator.generate(&ir, &kotlin_out).unwrap();

    let package_out = kotlin_out.join("game_config");
    let reward = std::fs::read_to_string(package_out.join("Reward.kt")).unwrap();
    assert!(reward.contains("class RewardTable private constructor"));
    assert!(reward.contains(") : AbstractList<Reward>(), SoraTable"));
    assert!(reward.contains("override fun get(index: Int): Reward = rows[index]"));
    assert!(!reward.contains("List<Reward> by rows"));

    let _ = std::fs::remove_dir_all(base);
}

#[test]
fn rust_config_api_can_use_fx_hash_map() {
    let mut ir = example_ir();
    ir.codegen.rust.map_type = sora_ir::model::RustMapTypeIr::FxHashMap;
    let base = temp_dir();
    let rust_out = base.join("rust");

    RustCodeGenerator.generate(&ir, &rust_out).unwrap();

    let rust_mod = std::fs::read_to_string(rust_out.join("mod.rs")).unwrap();
    let rust_item = std::fs::read_to_string(rust_out.join("item.rs")).unwrap();
    assert!(rust_mod.contains("pub type SoraMap<K, V> = rustc_hash::FxHashMap<K, V>;"));
    assert!(rust_item.contains("pub struct ItemTable"));
    assert!(rust_item.contains("rows: SoraMap<i32, Item>"));
    assert!(rust_mod.contains("tables: SoraMap<&'static str, Box<dyn SoraTable>>"));

    let _ = std::fs::remove_dir_all(base);
}

#[test]
fn csharp_supports_export_runtime_formats() {
    for (runtime_format, parse_function) in [
        (RuntimeFormatIr::Json, "ParseJson"),
        (RuntimeFormatIr::Cbor, "ParseCbor"),
        (RuntimeFormatIr::SoraProtobuf, "ParseProtobuf"),
    ] {
        let mut ir = example_ir();
        ir.codegen.csharp.runtime_format = runtime_format;
        let base = temp_dir();
        let csharp_out = base.join("csharp");

        CSharpCodeGenerator.generate(&ir, &csharp_out).unwrap();

        let runtime = std::fs::read_to_string(csharp_out.join("Runtime.cs")).unwrap();
        let config = std::fs::read_to_string(csharp_out.join("SoraConfig.cs")).unwrap();
        let item = std::fs::read_to_string(csharp_out.join("Item.cs")).unwrap();
        let action = std::fs::read_to_string(csharp_out.join("Action.cs")).unwrap();

        assert!(runtime.contains("public interface ISoraTableSource"));
        assert!(runtime.contains("public sealed class SoraValueBundle"));
        assert!(runtime.contains(parse_function));
        assert!(!config.contains(&format!("SoraValueBundle.{parse_function}(bytes)")));
        assert!(config.contains("FromSource(ISoraTableSource source)"));
        assert!(item.contains("internal static Item Decode(SoraValue value)"));
        assert!(item.contains("obj.Get(\"id\").AsInt32()"));
        assert!(item.contains("ItemTypeCodec.Decode(obj.Get(\"item_type\"))"));
        assert!(action.contains("internal static Action Decode(SoraValue value)"));

        let _ = std::fs::remove_dir_all(base);
    }
}

#[test]
fn kotlin_supports_export_runtime_formats() {
    for (runtime_format, parse_function) in [
        (RuntimeFormatIr::Json, "parseJson"),
        (RuntimeFormatIr::Cbor, "parseCbor"),
        (RuntimeFormatIr::SoraProtobuf, "parseProtobuf"),
    ] {
        let mut ir = example_ir();
        ir.codegen.kotlin.runtime_format = runtime_format;
        let base = temp_dir();
        let kotlin_out = base.join("kotlin");

        KotlinCodeGenerator.generate(&ir, &kotlin_out).unwrap();

        let package_out = kotlin_out.join("game_config");
        let runtime = std::fs::read_to_string(package_out.join("Runtime.kt")).unwrap();
        let config = std::fs::read_to_string(package_out.join("SoraConfig.kt")).unwrap();
        let item = std::fs::read_to_string(package_out.join("Item.kt")).unwrap();
        let action = std::fs::read_to_string(package_out.join("Action.kt")).unwrap();

        assert!(runtime.contains("class SoraValueBundle"));
        assert!(runtime.contains(parse_function));
        assert!(!config.contains(&format!("SoraValueBundle.{parse_function}(bytes)")));
        assert!(config.contains("fun fromSource(source: SoraTableSource): SoraConfig"));
        assert!(item.contains("fun decode(value: SoraValue): Item"));
        assert!(item.contains("obj.get(\"id\").asInt()"));
        assert!(item.contains("ItemType.decode(obj.get(\"item_type\"))"));
        assert!(action.contains("fun decode(value: SoraValue): Action"));

        let _ = std::fs::remove_dir_all(base);
    }
}

#[test]
fn go_supports_export_runtime_formats() {
    for (runtime_format, parse_function) in [
        (RuntimeFormatIr::Json, "ParseJsonBundle"),
        (RuntimeFormatIr::Cbor, "ParseCborBundle"),
        (RuntimeFormatIr::SoraProtobuf, "ParseProtobufBundle"),
    ] {
        let mut ir = example_ir();
        ir.codegen.go.runtime_format = runtime_format;
        let base = temp_dir();
        let go_out = base.join("go");

        GoCodeGenerator.generate(&ir, &go_out).unwrap();

        let runtime = std::fs::read_to_string(go_out.join("runtime.go")).unwrap();
        let config = std::fs::read_to_string(go_out.join("config.go")).unwrap();
        let item = std::fs::read_to_string(go_out.join("item.go")).unwrap();
        let action = std::fs::read_to_string(go_out.join("action.go")).unwrap();

        assert!(runtime.contains("type SoraValueBundle struct"));
        assert!(runtime.contains(parse_function));
        assert!(!config.contains(&format!("{parse_function}(bytes)")));
        assert!(runtime.contains("type SoraTableSource interface"));
        assert!(config.contains("func NewSoraConfigFromSource(source SoraTableSource)"));
        assert!(item.contains("func decodeItemValue(input SoraValue) (Item, error)"));
        assert!(item.contains("obj.Get(\"id\").AsInt32()"));
        assert!(item.contains("decodeItemTypeValue(obj.Get(\"item_type\"))"));
        assert!(action.contains("func decodeActionValue(input SoraValue) (Action, error)"));

        let _ = std::fs::remove_dir_all(base);
    }
}

#[test]
fn java_supports_export_runtime_formats() {
    for (runtime_format, parse_function) in [
        (RuntimeFormatIr::Json, "parseJson"),
        (RuntimeFormatIr::Cbor, "parseCbor"),
        (RuntimeFormatIr::SoraProtobuf, "parseProtobuf"),
    ] {
        let mut ir = example_ir();
        ir.codegen.java.runtime_format = runtime_format;
        let base = temp_dir();
        let java_out = base.join("java");

        JavaCodeGenerator.generate(&ir, &java_out).unwrap();

        let package_out = java_out.join("game_config");
        let runtime = std::fs::read_to_string(package_out.join("Runtime.java")).unwrap();
        let config = std::fs::read_to_string(package_out.join("SoraConfig.java")).unwrap();
        let item = std::fs::read_to_string(package_out.join("Item.java")).unwrap();
        let action = std::fs::read_to_string(package_out.join("Action.java")).unwrap();

        assert!(runtime.contains("final class SoraValueBundle"));
        assert!(runtime.contains(parse_function));
        assert!(!config.contains(&format!("SoraValueBundle.{parse_function}(bytes)")));
        assert!(runtime.contains("interface SoraTableSource"));
        assert!(config.contains("fromSource(SoraTableSource source)"));
        assert!(item.contains("static Item decode(SoraValue value)"));
        assert!(item.contains("obj.get(\"id\").asInt()"));
        assert!(item.contains("ItemType.decode(obj.get(\"item_type\"))"));
        assert!(action.contains("static Action decode(SoraValue value)"));

        let _ = std::fs::remove_dir_all(base);
    }
}

#[test]
fn generates_csharp_java_and_go_files() {
    let mut ir = example_ir();
    ir.package = "com.sora.game_config".to_owned();
    let base = temp_dir();
    let csharp_out = base.join("csharp");
    let java_out = base.join("java");
    let go_out = base.join("go");

    CSharpCodeGenerator.generate(&ir, &csharp_out).unwrap();
    JavaCodeGenerator.generate(&ir, &java_out).unwrap();
    GoCodeGenerator.generate(&ir, &go_out).unwrap();

    let csharp_item = std::fs::read_to_string(csharp_out.join("Item.cs")).unwrap();
    let csharp_config = std::fs::read_to_string(csharp_out.join("SoraConfig.cs")).unwrap();
    let java_item =
        std::fs::read_to_string(java_out.join("com/sora/game_config/Item.java")).unwrap();
    let java_config =
        std::fs::read_to_string(java_out.join("com/sora/game_config/SoraConfig.java")).unwrap();
    let go_item = std::fs::read_to_string(go_out.join("item.go")).unwrap();
    let go_config = std::fs::read_to_string(go_out.join("config.go")).unwrap();

    assert!(csharp_item.starts_with("// This file was generated by Sora. Do not edit manually."));
    assert!(csharp_item.contains("namespace com.sora.game_config;"));
    assert!(csharp_item.contains("public sealed record Item"));
    assert!(csharp_item.contains("// Item id"));
    assert!(
        csharp_item
            .contains("public sealed class ItemTable : ISoraTable, IReadOnlyDictionary<int, Item>")
    );
    assert!(csharp_item.contains("Dictionary<int, Item>"));
    assert!(csharp_item.contains("private readonly List<int> keys"));
    assert_contains_before(
        &csharp_item,
        "private readonly List<int> keys",
        "private readonly Dictionary<int, Item> rows",
    );
    assert!(csharp_item.contains("private readonly Dictionary<string, Item> byName"));
    assert!(csharp_item.contains("private readonly Dictionary<ItemType, List<Item>> byItemType"));
    assert!(csharp_item.contains("public Item? GetByName(string name)"));
    assert!(csharp_item.contains("public IReadOnlyList<int> OrderedKeys => keys"));
    assert!(csharp_item.contains("public IEnumerable<int> Keys => keys"));
    assert!(csharp_item.contains("public IEnumerator<KeyValuePair<int, Item>> GetEnumerator()"));
    assert!(csharp_item.contains("public IReadOnlyList<Item> FindByItemType(ItemType itemType)"));
    assert!(csharp_config.contains("public sealed class SoraConfig"));
    assert!(!csharp_config.contains("public sealed class ItemTable"));
    assert!(csharp_config.contains("public ItemTable Item => Table<ItemTable>(\"Item\")"));
    assert!(java_item.starts_with("// This file was generated by Sora. Do not edit manually."));
    assert!(java_item.contains("package com.sora.game_config;"));
    assert!(java_item.contains("public final class Item"));
    assert!(java_item.contains("/** Item id */"));
    assert!(java_item.contains(
        "final class ItemTable extends java.util.AbstractMap<Integer, Item> implements SoraTable"
    ));
    assert!(java_item.contains("java.util.Map<Integer, Item>"));
    assert!(java_item.contains("private final List<Integer> keys"));
    assert_contains_before(
        &java_item,
        "private final List<Integer> keys",
        "private final java.util.Map<Integer, Item> rows",
    );
    assert!(java_item.contains("private final Map<String, Item> byName"));
    assert!(java_item.contains("private final Map<ItemType, List<Item>> byItemType"));
    assert!(java_item.contains("public Item getByName(String name)"));
    assert!(java_item.contains("public List<Integer> keys()"));
    assert!(java_item.contains("public java.util.Set<Map.Entry<Integer, Item>> entrySet()"));
    assert!(java_item.contains("public List<Item> findByItemType(ItemType itemType)"));
    assert!(java_config.contains("public final class SoraConfig"));
    assert!(!java_config.contains("final class ItemTable extends java.util.AbstractMap"));
    assert!(java_config.contains("public ItemTable item()"));
    assert!(go_item.starts_with("// This file was generated by Sora. Do not edit manually."));
    assert!(go_item.contains("package game_config"));
    assert!(go_item.contains("type Item struct"));
    assert!(go_item.contains("// Id: Item id"));
    assert!(go_item.contains("type ItemTable struct"));
    assert!(go_item.contains("map[int32]Item"));
    assert!(go_item.contains("keys []int32"));
    assert_contains_before(&go_item, "keys []int32", "rows map[int32]Item");
    assert!(go_item.contains("byName map[string]Item"));
    assert!(go_item.contains("byItemType map[ItemType][]Item"));
    assert!(go_item.contains("func (table *ItemTable) GetByName(name string) (Item, bool)"));
    assert!(go_item.contains("func (table *ItemTable) Keys() []int32"));
    assert!(go_item.contains("func (table *ItemTable) FindByItemType(itemType ItemType) []Item"));
    assert!(go_config.contains("type SoraConfig struct"));
    assert!(!go_config.contains("type ItemTable struct"));
    assert!(go_config.contains("func NewSoraConfigFromSource(source SoraTableSource)"));
    assert!(go_config.contains("func (config *SoraConfig) Item() *ItemTable"));

    let _ = std::fs::remove_dir_all(base);
}

fn example_ir() -> ConfigIr {
    let schema: SchemaFile = toml::from_str(
        r#"
package = "game_config"

[[enums]]
name = "ItemType"
values = ["Weapon", "Armor", "Material", "Consumable"]

[[unions]]
name = "Action"

[[unions.variants]]
name = "AddItem"

[[unions.variants.fields]]
name = "item_id"
type = "i32"

[[tables]]
name = "Item"
mode = "map"
key = "id"

[[tables.fields]]
name = "id"
type = "i32"
key = true
required = true
comment = "Item id"

[[tables.fields]]
name = "name"
type = "string"
required = true
comment = "Item name"

[[tables.fields]]
name = "item_type"
type = "enum<ItemType>"
required = true
comment = "Item type"

[[tables.fields]]
name = "action"
type = "union<Action>"
required = true
comment = "Action"

[[tables.indexes]]
name = "by_name"
fields = ["name"]
unique = true

[[tables.indexes]]
name = "by_item_type"
fields = ["item_type"]
"#,
    )
    .unwrap();

    normalize_schema(schema).unwrap()
}

fn table_mode_ir() -> ConfigIr {
    let schema: SchemaFile = toml::from_str(
        r#"
package = "game_config"

[[tables]]
name = "Item"
mode = "map"
key = "id"

[[tables.fields]]
name = "id"
type = "i32"
required = true

[[tables]]
name = "Settings"
mode = "singleton"

[[tables.fields]]
name = "version"
type = "string"
required = true

[[tables]]
name = "Reward"
mode = "list"

[[tables.fields]]
name = "id"
type = "i32"
required = true
"#,
    )
    .unwrap();

    normalize_schema(schema).unwrap()
}

fn temp_dir() -> PathBuf {
    let unique = TEMP_COUNTER.fetch_add(1, Ordering::Relaxed);
    std::env::temp_dir().join(format!("sora-codegen-test-{unique}"))
}

fn assert_contains_before(haystack: &str, first: &str, second: &str) {
    let first_index = haystack
        .find(first)
        .unwrap_or_else(|| panic!("expected output to contain `{first}`"));
    let second_index = haystack
        .find(second)
        .unwrap_or_else(|| panic!("expected output to contain `{second}`"));
    assert!(
        first_index < second_index,
        "expected `{first}` to appear before `{second}`"
    );
}
