use std::path::Path;

use heck::{ToShoutySnakeCase, ToSnakeCase, ToUpperCamelCase};
use sora_diagnostics::Result;
use sora_ir::model::{ConfigIr, FieldIr, TypeIr};

use crate::{
    generator::{CodeGenerator, CodegenContext},
    options::{ProtoCodegenOptions, required_binding},
    render::{ensure_dir, write_file},
};

pub struct ProtoCodeGenerator;
crate::impl_test_codegen_generate!(ProtoCodeGenerator, "proto-schema");

impl CodeGenerator for ProtoCodeGenerator {
    fn generate(&self, context: CodegenContext<'_>, out_dir: &Path) -> Result<()> {
        let ir = context.ir;
        let options = context.options::<ProtoCodegenOptions>()?;
        let package = required_binding("proto-schema", "package", options.package)?;
        ensure_dir(out_dir)?;
        write_file(
            &out_dir.join("sora_config.proto"),
            render_proto(ir, &package),
        )
    }
}

fn render_proto(ir: &ConfigIr, package: &str) -> String {
    let mut output = String::new();
    output.push_str("// This file was generated by Sora. Do not edit manually.\n\n");
    output.push_str("syntax = \"proto3\";\n\n");
    output.push_str(&format!("package {package};\n\n"));

    output.push_str("message SoraConfigData {\n");
    for (index, table) in ir.tables.iter().enumerate() {
        let field_name = table.name.to_snake_case();
        let message_name = &table.name;
        if matches!(table.mode, sora_ir::model::TableModeIr::Singleton) {
            output.push_str(&format!("  {message_name} {field_name} = {};\n", index + 1));
        } else {
            output.push_str(&format!(
                "  repeated {message_name} {field_name} = {};\n",
                index + 1
            ));
        }
    }
    output.push_str("}\n\n");

    for item in &ir.enums {
        if let Some(comment) = &item.comment {
            output.push_str(&format!("// {comment}\n"));
        }
        output.push_str(&format!("enum {} {{\n", item.name));
        let prefix = item.name.to_shouty_snake_case();
        if !item.values.iter().any(|value| value.id == 0) {
            output.push_str(&format!("  {prefix}_UNSPECIFIED = 0;\n"));
        }
        for value in item
            .values
            .iter()
            .filter(|value| value.id == 0)
            .chain(item.values.iter().filter(|value| value.id != 0))
        {
            if let Some(comment) = &value.comment {
                output.push_str(&format!("  // {comment}\n"));
            }
            output.push_str(&format!(
                "  {prefix}_{} = {};\n",
                value.name.to_shouty_snake_case(),
                value.id
            ));
        }
        output.push_str("}\n\n");
    }

    for item in &ir.structs {
        output.push_str(&render_message(ir, &item.name, &item.fields));
    }

    for item in &ir.unions {
        output.push_str(&format!("message {} {{\n", item.name));
        output.push_str("  oneof kind {\n");
        for (index, variant) in item.variants.iter().enumerate() {
            output.push_str(&format!(
                "    {}{} {} = {};\n",
                item.name,
                variant.name,
                variant.name.to_snake_case(),
                index + 1
            ));
        }
        output.push_str("  }\n");
        output.push_str("}\n\n");

        for variant in &item.variants {
            output.push_str(&render_message(
                ir,
                &format!("{}{}", item.name, variant.name),
                &variant.fields,
            ));
        }
    }

    for table in &ir.tables {
        output.push_str(&render_message(ir, &table.name, &table.fields));
    }

    output
}

fn render_message(ir: &ConfigIr, name: &str, fields: &[FieldIr]) -> String {
    let mut output = String::new();
    output.push_str(&format!("message {name} {{\n"));
    for (index, field) in fields.iter().enumerate() {
        output.push_str(&render_field(
            ir,
            &field.name.to_snake_case(),
            &field.ty,
            index + 1,
            "  ",
        ));
    }
    output.push_str("}\n\n");
    output
}

fn render_field(ir: &ConfigIr, name: &str, ty: &TypeIr, tag: usize, indent: &str) -> String {
    if let TypeIr::Map { key, value } = ty {
        if supports_native_proto_map(ir, key, value) {
            return format!(
                "{indent}map<{}, {}> {name} = {tag};\n",
                proto_type(ir, key),
                proto_type(ir, value)
            );
        }

        let entry_name = format!("{}Entry", name.to_upper_camel_case());
        let child_indent = format!("{indent}  ");
        let mut output = format!("{indent}message {entry_name} {{\n");
        output.push_str(&render_field(ir, "key", key, 1, &child_indent));
        output.push_str(&render_field(ir, "value", value, 2, &child_indent));
        output.push_str(&format!("{indent}}}\n"));
        output.push_str(&format!("{indent}repeated {entry_name} {name} = {tag};\n"));
        return output;
    }

    format!(
        "{indent}{}{} {name} = {tag};\n",
        proto_label(ir, ty),
        proto_type(ir, ty)
    )
}

fn proto_label(ir: &ConfigIr, ty: &TypeIr) -> &'static str {
    match ty {
        TypeIr::List(_) | TypeIr::Set(_) | TypeIr::Array { .. } => "repeated ",
        TypeIr::Optional(element) if supports_proto_optional(ir, element) => "optional ",
        _ => "",
    }
}

fn supports_native_proto_map(ir: &ConfigIr, key: &TypeIr, value: &TypeIr) -> bool {
    is_proto_map_key(ir, key) && is_proto_map_value(ir, value)
}

fn is_proto_map_key(ir: &ConfigIr, ty: &TypeIr) -> bool {
    match ty {
        TypeIr::Bool
        | TypeIr::I8
        | TypeIr::U8
        | TypeIr::I16
        | TypeIr::U16
        | TypeIr::I32
        | TypeIr::U32
        | TypeIr::I64
        | TypeIr::Duration
        | TypeIr::DateTime
        | TypeIr::String
        | TypeIr::Text => true,
        TypeIr::Ref { table, field } => is_proto_map_key(ir, ref_type(ir, table, field)),
        _ => false,
    }
}

fn is_proto_map_value(ir: &ConfigIr, ty: &TypeIr) -> bool {
    match ty {
        TypeIr::List(_) | TypeIr::Set(_) | TypeIr::Map { .. } | TypeIr::Array { .. } => false,
        TypeIr::Optional(element) => is_proto_map_value(ir, element),
        TypeIr::Ref { table, field } => is_proto_map_value(ir, ref_type(ir, table, field)),
        _ => true,
    }
}

fn supports_proto_optional(ir: &ConfigIr, ty: &TypeIr) -> bool {
    match ty {
        TypeIr::Bool
        | TypeIr::I8
        | TypeIr::U8
        | TypeIr::I16
        | TypeIr::U16
        | TypeIr::I32
        | TypeIr::U32
        | TypeIr::I64
        | TypeIr::Duration
        | TypeIr::DateTime
        | TypeIr::F32
        | TypeIr::F64
        | TypeIr::String
        | TypeIr::Text
        | TypeIr::Enum(_) => true,
        TypeIr::Ref { table, field } => supports_proto_optional(ir, ref_type(ir, table, field)),
        _ => false,
    }
}

fn proto_type(ir: &ConfigIr, ty: &TypeIr) -> String {
    match ty {
        TypeIr::Bool => "bool".to_owned(),
        TypeIr::I8 | TypeIr::I16 | TypeIr::I32 => "int32".to_owned(),
        TypeIr::U8 | TypeIr::U16 | TypeIr::U32 => "uint32".to_owned(),
        TypeIr::I64 | TypeIr::Duration | TypeIr::DateTime => "int64".to_owned(),
        TypeIr::F32 => "float".to_owned(),
        TypeIr::F64 => "double".to_owned(),
        TypeIr::String | TypeIr::Text => "string".to_owned(),
        TypeIr::Enum(name) | TypeIr::Struct(name) | TypeIr::Union(name) => name.clone(),
        TypeIr::List(element)
        | TypeIr::Set(element)
        | TypeIr::Array { element, .. }
        | TypeIr::Optional(element) => proto_type(ir, element),
        TypeIr::Map { .. } => unreachable!("map fields are rendered by render_field"),
        TypeIr::Ref { table, field } => proto_type(ir, ref_type(ir, table, field)),
    }
}

fn ref_type<'a>(ir: &'a ConfigIr, table_name: &str, field_name: &str) -> &'a TypeIr {
    ir.tables
        .iter()
        .find(|table| table.name == table_name)
        .and_then(|table| table.fields.iter().find(|field| field.name == field_name))
        .map(|field| &field.ty)
        .unwrap_or(&TypeIr::I32)
}

#[cfg(test)]
mod tests {
    use super::*;
    use sora_ir::normalize::normalize_schema;
    use sora_schema::model::ProjectSchema;

    #[test]
    fn generates_business_proto_schema() {
        let schema: ProjectSchema = toml::from_str(
            r#"
project = { id = "com.sora.game" }
groups = { common = { default = true } }
views = { default = { contract = "com.sora.game/default", groups = ["common"] } }

[[enums]]
name = "ItemType"
values = [{ id = 10, name = "Weapon" }, { id = 20, name = "Armor" }]

[[structs]]
name = "Cost"

[[structs.fields]]
name = "item_id"
type = "i32"

[[unions]]
name = "Action"

[[unions.variants]]
name = "AddItem"

[[unions.variants.fields]]
name = "item_id"
type = "i32"

[[tables]]
id = "item"
name = "Item"
mode = "map"
key = "id"

[[tables.fields]]
name = "id"
type = "i32"

[[tables.fields]]
name = "item_type"
type = "enum<ItemType>"

[[tables.fields]]
name = "tags"
type = "list<string>"

[[tables.fields]]
name = "action"
type = "union<Action>"

[[tables.fields]]
name = "attributes"
type = "map<string,i32>"

[[tables.fields]]
name = "rewards"
type = "map<enum<ItemType>,list<i32>>"
"#,
        )
        .unwrap();
        let ir = normalize_schema(schema).unwrap();

        let proto = render_proto(&ir, "com.sora.game");

        assert!(proto.contains("syntax = \"proto3\";"));
        assert!(proto.contains("package com.sora.game;"));
        assert!(proto.contains("message SoraConfigData"));
        assert!(proto.contains("repeated Item item = 1;"));
        assert!(proto.contains("enum ItemType"));
        assert!(proto.contains("ITEM_TYPE_UNSPECIFIED = 0;"));
        assert!(proto.contains("ITEM_TYPE_WEAPON = 10;"));
        assert!(proto.contains("message Action"));
        assert!(proto.contains("oneof kind"));
        assert!(proto.contains("ActionAddItem add_item = 1;"));
        assert!(proto.contains("repeated string tags = 3;"));
        assert!(proto.contains("map<string, int32> attributes = 5;"));
        assert!(proto.contains("message RewardsEntry"));
        assert!(proto.contains("ItemType key = 1;"));
        assert!(proto.contains("repeated int32 value = 2;"));
        assert!(proto.contains("repeated RewardsEntry rewards = 6;"));
    }
}
