use std::{
    collections::{BTreeMap, BTreeSet},
    path::{Path, PathBuf},
};

use heck::ToPascalCase;
use minijinja::context;
use serde::Serialize;
use sora_diagnostics::{Result, SoraError};
use sora_ir::key::{TableKeyIdentity, resolve_ref_key_identity, resolve_table_key_identity};
use sora_ir::model::{ConfigIr, TableModeIr, TypeIr};

use crate::{
    generator::{CodeGenerator, CodegenContext, runtime_format_name},
    model::{
        BaseEnumValue, BaseField, BaseIndex, BaseModel, BaseRecord, BaseTable, BaseUnion,
        BaseUnionVariant, build_base_model, schema_local_name, schema_module_path,
    },
    options::{
        RuntimeFormat, RustCodegenOptions, RustCrateOptions, RustDateTimeType, RustMapType,
        RustStringStorage,
    },
    render::{ensure_dir, render_template, write_file},
    type_mapping::{TypeMapping, TypeMappingContext, TypeMappingRegistry},
};

pub struct RustCodeGenerator;
crate::impl_test_codegen_generate!(RustCodeGenerator, "rust");

impl CodeGenerator for RustCodeGenerator {
    fn generate(&self, context: CodegenContext<'_>, out_dir: &Path) -> Result<()> {
        let ir = context.ir;
        let options = context.options::<RustCodegenOptions>()?;
        let source_dir = rust_source_dir(out_dir, &options)?;
        ensure_dir(&source_dir)?;
        let mapper = RustTypeMapper::new(context.target, ir, context.type_mappings, &options);
        let model = RustModel::from_base_model(ir, build_base_model(ir)?, &mapper)?;
        let runtime_format = runtime_format_name(options.runtime_format);

        for item in &model.enums {
            let rendered = render_template("rust", "enum.rs.j2", context! { enum => item })?;
            write_file(
                &source_dir.join(format!("{}.rs", item.module_path)),
                rendered,
            )?;
        }

        for record in &model.records {
            let rendered = render_template("rust", "struct.rs.j2", context! { record => record })?;
            write_file(
                &source_dir.join(format!("{}.rs", record.module_path)),
                rendered,
            )?;
        }

        for union in &model.unions {
            let rendered = render_template("rust", "union.rs.j2", context! { union => union })?;
            write_file(
                &source_dir.join(format!("{}.rs", union.module_path)),
                rendered,
            )?;
        }

        let rust_map_type = match options.map_type {
            RustMapType::Std => "std",
            RustMapType::FxHashMap => "fx_hash_map",
        };
        let rendered = render_template(
            "rust",
            "mod.rs.j2",
            context! { model => &model, rust_map_type => rust_map_type, runtime_format => runtime_format },
        )?;
        let root_file = if options.crate_options.is_some() {
            "lib.rs"
        } else {
            "mod.rs"
        };
        write_file(&source_dir.join(root_file), rendered)?;
        write_rust_namespace_modules(&source_dir, &model)?;

        let rendered = render_template(
            "rust",
            "runtime.rs.j2",
            context! {
                runtime_format => runtime_format,
                string_storage => rust_string_storage_name(options.string_storage),
                datetime_type => rust_datetime_type_name(options.datetime_type),
            },
        )?;
        write_file(&source_dir.join("runtime.rs"), rendered)?;

        if let Some(package) = &options.crate_options {
            let manifest = RustCrateManifest::new(package, &options);
            let rendered =
                render_template("rust", "Cargo.toml.j2", context! { package => &manifest })?;
            write_file(&out_dir.join("Cargo.toml"), rendered)?;
        }

        Ok(())
    }
}

fn write_rust_namespace_modules(source_dir: &Path, model: &RustModel) -> Result<()> {
    let mut children = BTreeMap::<String, BTreeSet<String>>::new();

    for item in &model.enums {
        register_rust_module(&item.module_path, &mut children);
    }
    for item in &model.unions {
        register_rust_module(&item.module_path, &mut children);
    }
    for item in &model.records {
        register_rust_module(&item.module_path, &mut children);
    }

    for (namespace, modules) in children {
        if namespace.is_empty() {
            continue;
        }
        let mut rendered =
            String::from("// This file was generated by Sora. Do not edit manually.\n\n");
        for module in modules {
            rendered.push_str(&format!("pub mod {module};\n"));
        }
        write_file(&source_dir.join(namespace).join("mod.rs"), rendered)?;
    }
    Ok(())
}

fn register_rust_module(module_path: &str, children: &mut BTreeMap<String, BTreeSet<String>>) {
    let segments = module_path.split('/').collect::<Vec<_>>();
    for index in 0..segments.len() {
        let parent = segments[..index].join("/");
        children
            .entry(parent)
            .or_default()
            .insert(segments[index].to_owned());
    }
}

fn rust_source_dir(out_dir: &Path, options: &RustCodegenOptions) -> Result<PathBuf> {
    if let Some(package) = &options.crate_options {
        validate_rust_crate_options(package)?;
        Ok(out_dir.join("src"))
    } else {
        Ok(out_dir.to_path_buf())
    }
}

fn validate_rust_crate_options(package: &RustCrateOptions) -> Result<()> {
    let name = package.name.as_str();
    let valid_name = name
        .bytes()
        .next()
        .is_some_and(|first| first.is_ascii_alphabetic())
        && name
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'));
    if !valid_name {
        return Err(SoraError::InvalidSchema(format!(
            "invalid Rust crate name `{name}`: expected an ASCII letter followed by ASCII letters, digits, `-`, or `_`"
        )));
    }
    semver::Version::parse(&package.version).map_err(|error| {
        SoraError::InvalidSchema(format!(
            "invalid Rust crate version `{}`: {error}",
            package.version
        ))
    })?;
    Ok(())
}

#[derive(Debug, Serialize)]
struct RustCrateManifest<'a> {
    name: &'a str,
    version: &'a str,
    edition: &'static str,
    publish: bool,
    uses_rustc_hash: bool,
    uses_chrono: bool,
    uses_serde_json: bool,
    uses_serde_cbor: bool,
    uses_prost: bool,
}

impl<'a> RustCrateManifest<'a> {
    fn new(package: &'a RustCrateOptions, options: &RustCodegenOptions) -> Self {
        Self {
            name: &package.name,
            version: &package.version,
            edition: package.edition.as_str(),
            publish: package.publish,
            uses_rustc_hash: options.map_type == RustMapType::FxHashMap,
            uses_chrono: options.datetime_type == RustDateTimeType::Chrono,
            uses_serde_json: matches!(
                options.runtime_format,
                RuntimeFormat::Json | RuntimeFormat::Cbor | RuntimeFormat::SoraProtobuf
            ),
            uses_serde_cbor: options.runtime_format == RuntimeFormat::Cbor,
            uses_prost: options.runtime_format == RuntimeFormat::SoraProtobuf,
        }
    }
}

#[derive(Debug, Clone, Serialize)]
struct RustModel {
    package: String,
    schema_fingerprint: String,
    enums: Vec<RustEnum>,
    unions: Vec<RustUnion>,
    records: Vec<RustRecord>,
    tables: Vec<RustTable>,
    modules: Vec<String>,
    has_map_tables: bool,
    has_singleton_tables: bool,
    has_unique_indexes: bool,
    has_non_unique_list_indexes: bool,
    has_non_unique_map_indexes: bool,
    has_localization: bool,
    locales: Vec<String>,
    default_locale: String,
}

#[derive(Debug, Clone, Serialize)]
struct RustEnum {
    name: String,
    snake_name: String,
    module_path: String,
    root_path: String,
    comment: Option<String>,
    values: Vec<BaseEnumValue>,
}

#[derive(Debug, Clone, Serialize)]
struct RustUnion {
    pascal_name: String,
    snake_name: String,
    module_path: String,
    root_path: String,
    tag: String,
    variants: Vec<RustUnionVariant>,
    imports: Vec<RustImport>,
    custom_imports: Vec<String>,
}

#[derive(Debug, Clone, Serialize)]
struct RustUnionVariant {
    name: String,
    fields: Vec<RustField>,
    text_key_patterns: String,
}

#[derive(Debug, Clone, Serialize)]
struct RustRecord {
    pascal_name: String,
    snake_name: String,
    module_path: String,
    root_path: String,
    imports: Vec<RustImport>,
    custom_imports: Vec<String>,
    fields: Vec<RustField>,
    table: Option<RustTable>,
}

#[derive(Debug, Clone, Serialize)]
struct RustStrongKey {
    name: String,
    raw_type: String,
    copy: bool,
    const_raw: bool,
    string_like: bool,
    text: bool,
    serde_with: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
struct RustImport {
    module: String,
    name: String,
}

#[derive(Debug, Clone, Serialize)]
struct RustTable {
    name: String,
    module_path: String,
    pascal_name: String,
    snake_name: String,
    mode: String,
    container_type: String,
    row_type: String,
    row_path: String,
    table_path: String,
    key_name: Option<String>,
    key_field_name: Option<String>,
    key_type: Option<String>,
    key_is_copy: bool,
    key_string_like: bool,
    strong_key: Option<RustStrongKey>,
    unique_indexes: Vec<RustIndex>,
    non_unique_indexes: Vec<RustIndex>,
}

#[derive(Debug, Clone, Serialize)]
struct RustIndex {
    name: String,
    method_name: String,
    field_name: String,
    param_name: String,
    param_type: String,
    key_type: String,
    key_is_copy: bool,
}

#[derive(Debug, Clone, Serialize)]
struct RustField {
    raw_name: String,
    name: String,
    type_name: String,
    serde_with: Option<String>,
    decode: String,
    collect_text_keys: String,
    text_key_binding: String,
    imports: Vec<String>,
    comment: Option<String>,
}

impl RustModel {
    fn from_base_model(
        ir: &ConfigIr,
        model: BaseModel,
        mapper: &RustTypeMapper<'_>,
    ) -> Result<Self> {
        let root_modules = model
            .modules
            .iter()
            .filter_map(|module| module.split('/').next())
            .map(str::to_owned)
            .collect::<BTreeSet<_>>()
            .into_iter()
            .collect::<Vec<_>>();
        let tables = model
            .tables
            .into_iter()
            .map(|item| rust_table(ir, item, mapper))
            .collect::<Result<Vec<_>>>()?;
        Ok(Self {
            package: model.package,
            schema_fingerprint: model.schema_fingerprint,
            enums: model
                .enums
                .into_iter()
                .map(|item| RustEnum {
                    root_path: rust_module_root(&item.module_path),
                    name: item.pascal_name,
                    snake_name: item.snake_name,
                    module_path: item.module_path,
                    comment: item.comment,
                    values: item.values,
                })
                .collect(),
            unions: model
                .unions
                .into_iter()
                .map(|item| rust_union(ir, item, mapper))
                .collect(),
            records: model
                .records
                .into_iter()
                .map(|item| {
                    let table = tables
                        .iter()
                        .find(|table| table.module_path == item.module_path)
                        .cloned();
                    rust_record(ir, item, table, mapper)
                })
                .collect(),
            has_map_tables: tables
                .iter()
                .any(|table| table.mode == "map" && table.key_field_name.is_some()),
            has_singleton_tables: tables.iter().any(|table| table.mode == "singleton"),
            has_unique_indexes: tables.iter().any(|table| !table.unique_indexes.is_empty()),
            has_non_unique_list_indexes: tables
                .iter()
                .any(|table| table.mode == "list" && !table.non_unique_indexes.is_empty()),
            has_non_unique_map_indexes: tables
                .iter()
                .any(|table| table.mode == "map" && !table.non_unique_indexes.is_empty()),
            has_localization: ir.localization.is_some(),
            locales: ir
                .localization
                .as_ref()
                .map(|item| item.locales.clone())
                .unwrap_or_default(),
            default_locale: ir
                .localization
                .as_ref()
                .map(|item| item.default_locale.clone())
                .unwrap_or_default(),
            tables,
            modules: root_modules,
        })
    }
}

fn rust_union(ir: &ConfigIr, union: BaseUnion, mapper: &RustTypeMapper<'_>) -> RustUnion {
    let root_path = rust_module_root(&union.module_path);
    let variants = union
        .variants
        .into_iter()
        .map(|variant| rust_variant(ir, variant, mapper, &root_path))
        .collect::<Vec<_>>();
    let custom_imports = collect_rust_imports(variants.iter().flat_map(|variant| &variant.fields));
    RustUnion {
        pascal_name: union.pascal_name,
        snake_name: union.snake_name,
        module_path: union.module_path,
        root_path,
        tag: union.tag,
        variants,
        imports: Vec::new(),
        custom_imports,
    }
}

fn rust_variant(
    ir: &ConfigIr,
    variant: BaseUnionVariant,
    mapper: &RustTypeMapper<'_>,
    root_path: &str,
) -> RustUnionVariant {
    let mut fields = variant
        .fields
        .into_iter()
        .map(|field| rust_field(ir, field, mapper, root_path, None, false, false))
        .collect::<Vec<_>>();
    for (index, field) in fields.iter_mut().enumerate() {
        field.text_key_binding = format!("__sora_text_field_{index}");
    }
    let text_key_patterns = fields
        .iter()
        .filter(|field| !field.collect_text_keys.is_empty())
        .map(|field| format!("{}: {}", field.name, field.text_key_binding))
        .collect::<Vec<_>>()
        .join(", ");
    RustUnionVariant {
        name: variant.pascal_name,
        fields,
        text_key_patterns,
    }
}

fn rust_record(
    ir: &ConfigIr,
    record: BaseRecord,
    table: Option<RustTable>,
    mapper: &RustTypeMapper<'_>,
) -> RustRecord {
    let root_path = rust_module_root(&record.module_path);
    let primary_key_name = table.as_ref().and_then(|table| table.key_name.as_deref());
    let primary_key_type = table.as_ref().and_then(|table| table.key_type.as_deref());
    let primary_key_is_text = table
        .as_ref()
        .and_then(|table| table.strong_key.as_ref())
        .is_some_and(|key| key.text);
    let primary_key_is_strong = table
        .as_ref()
        .is_some_and(|table| table.strong_key.is_some());
    let fields = record
        .fields
        .into_iter()
        .map(|field| {
            let is_primary_key = primary_key_name == Some(field.raw_name.as_str());
            rust_field(
                ir,
                field,
                mapper,
                &root_path,
                is_primary_key.then_some(primary_key_type).flatten(),
                is_primary_key && primary_key_is_strong,
                is_primary_key && primary_key_is_text,
            )
        })
        .collect::<Vec<_>>();
    let custom_imports = collect_rust_imports(fields.iter());
    RustRecord {
        pascal_name: record.pascal_name,
        snake_name: record.snake_name,
        module_path: record.module_path,
        root_path,
        imports: Vec::new(),
        custom_imports,
        fields,
        table,
    }
}

fn rust_table(ir: &ConfigIr, table: BaseTable, mapper: &RustTypeMapper<'_>) -> Result<RustTable> {
    let root_path = rust_module_root(&table.module_path);
    let row_type = table.pascal_name.clone();
    let rust_module_path = table.module_path.replace('/', "::");
    let row_path = format!("{rust_module_path}::{}", table.pascal_name);
    let table_path = format!("{rust_module_path}::{}Table", table.pascal_name);
    let key_identity = if table.mode == TableModeIr::Map {
        let table_ir = ir
            .tables
            .iter()
            .find(|candidate| candidate.name == table.name)
            .ok_or_else(|| {
                SoraError::InvalidSchema(format!(
                    "Rust codegen could not resolve map table `{}` in schema IR",
                    table.name
                ))
            })?;
        Some(resolve_table_key_identity(&ir.tables, table_ir)?)
    } else {
        None
    };
    let key_type = key_identity.as_ref().map(|identity| match identity {
        TableKeyIdentity::Primitive {
            table: owner,
            field,
            ..
        } if owner.name == table.name => strong_key_name(owner, field),
        _ => mapper.key_identity_type_name(*identity, &root_path),
    });
    let container_type = rust_container_type(table.mode, &row_type, key_type.as_deref());
    let key_field_name = table
        .key_field
        .as_ref()
        .map(|field| field.snake_name.clone());
    let key_name = table.key_name.clone();
    let key_is_copy = key_identity
        .as_ref()
        .is_some_and(|identity| mapper.key_identity_is_copy(*identity));
    let key_string_like = key_identity
        .as_ref()
        .is_some_and(|identity| mapper.key_identity_is_string_like(*identity));
    let strong_key = key_identity.and_then(|identity| match identity {
        TableKeyIdentity::Primitive {
            table: owner,
            field,
            raw_type,
        } if owner.name == table.name => {
            let name = strong_key_name(owner, field);
            Some(RustStrongKey {
                name,
                raw_type: mapper.type_name(raw_type, &root_path),
                copy: mapper.key_identity_is_copy(identity),
                const_raw: is_const_raw_type(raw_type),
                string_like: matches!(raw_type, TypeIr::String),
                text: matches!(raw_type, TypeIr::Text),
                serde_with: rust_serde_with(raw_type, mapper.options, &root_path),
            })
        }
        _ => None,
    });
    if let Some(key) = &strong_key
        && (key.name == row_type || key.name == format!("{row_type}Table"))
    {
        return Err(SoraError::InvalidSchema(format!(
            "Rust strong key type `{}` for table `{}` conflicts with a generated type in module `{}`",
            key.name, table.name, table.module_path
        )));
    }

    Ok(RustTable {
        name: table.name,
        module_path: table.module_path,
        pascal_name: table.pascal_name,
        snake_name: table.snake_name,
        mode: table.mode_name,
        container_type,
        row_type,
        row_path,
        table_path,
        key_name: key_name.clone(),
        key_field_name,
        key_type: key_type.clone(),
        key_is_copy,
        key_string_like,
        strong_key,
        unique_indexes: table
            .unique_indexes
            .into_iter()
            .map(|index| {
                rust_index(
                    index,
                    mapper,
                    &root_path,
                    key_name.as_deref(),
                    key_type.as_deref(),
                    key_is_copy,
                    key_string_like,
                )
            })
            .collect(),
        non_unique_indexes: table
            .non_unique_indexes
            .into_iter()
            .map(|index| {
                rust_index(
                    index,
                    mapper,
                    &root_path,
                    key_name.as_deref(),
                    key_type.as_deref(),
                    key_is_copy,
                    key_string_like,
                )
            })
            .collect(),
    })
}

fn rust_index(
    index: BaseIndex,
    mapper: &RustTypeMapper<'_>,
    root_path: &str,
    primary_key_name: Option<&str>,
    primary_key_type: Option<&str>,
    primary_key_is_copy: bool,
    primary_key_string_like: bool,
) -> RustIndex {
    let is_primary_key = primary_key_name == Some(index.field.raw_name.as_str());
    let key_type = if is_primary_key {
        primary_key_type
            .expect("map primary key type should be resolved")
            .to_owned()
    } else {
        mapper.local_table_key_type(&index.field.ty, root_path)
    };
    let key_is_copy = if is_primary_key {
        primary_key_is_copy
    } else {
        mapper.key_type_is_copy(&index.field.ty)
    };
    let param_type = if is_primary_key && primary_key_string_like {
        "str".to_owned()
    } else if is_primary_key {
        key_type.clone()
    } else {
        mapper.key_param_type(&index.field.ty, root_path)
    };
    RustIndex {
        name: index.snake_name,
        method_name: index.method_name,
        field_name: index.field.snake_name.clone(),
        param_name: index.field.snake_name.clone(),
        param_type,
        key_type,
        key_is_copy,
    }
}

fn rust_field(
    ir: &ConfigIr,
    field: BaseField,
    mapper: &RustTypeMapper<'_>,
    root_path: &str,
    primary_key_type: Option<&str>,
    primary_key_is_strong: bool,
    primary_key_is_text: bool,
) -> RustField {
    let type_name = primary_key_type
        .map(str::to_owned)
        .unwrap_or_else(|| mapper.type_name(&field.ty, root_path));
    let collect_text_keys = if primary_key_is_text {
        format!("out.push(self.{}.as_text_key());", field.snake_name)
    } else {
        rust_collect_text_keys(ir, &field.ty, &format!("self.{}", field.snake_name), mapper)
    };
    let decode = if primary_key_is_strong {
        format!("<{type_name} as {root_path}::runtime::SoraDecode>::decode(reader)?")
    } else {
        rust_decode_expr(ir, &field.ty, mapper, root_path)
    };
    RustField {
        raw_name: field.raw_name,
        name: field.snake_name,
        type_name,
        serde_with: (!primary_key_is_strong)
            .then(|| rust_serde_with(&field.ty, mapper.options, root_path))
            .flatten(),
        decode,
        collect_text_keys,
        text_key_binding: String::new(),
        imports: mapper.imports(&field.ty),
        comment: field.comment,
    }
}

fn collect_rust_imports<'a>(fields: impl Iterator<Item = &'a RustField>) -> Vec<String> {
    let mut imports = fields
        .flat_map(|field| field.imports.iter().cloned())
        .collect::<Vec<_>>();
    imports.sort();
    imports.dedup();
    imports
}

fn rust_collect_text_keys(
    ir: &ConfigIr,
    ty: &TypeIr,
    value: &str,
    mapper: &RustTypeMapper<'_>,
) -> String {
    if mapper.mapping(ty).is_some() {
        return String::new();
    }
    match ty {
        TypeIr::Text => format!("out.push(&{value});"),
        TypeIr::Optional(element) => {
            let inner = rust_collect_text_keys(ir, element, "value", mapper);
            if inner.is_empty() {
                String::new()
            } else {
                format!("if let Some(value) = &{value} {{ {inner} }}")
            }
        }
        TypeIr::List(element) | TypeIr::Set(element) | TypeIr::Array { element, .. } => {
            let inner = rust_collect_text_keys(ir, element, "value", mapper);
            if inner.is_empty() {
                String::new()
            } else {
                format!("for value in {value}.iter() {{ {inner} }}")
            }
        }
        TypeIr::Map {
            key,
            value: element,
        } => {
            let key_inner = rust_collect_text_keys(ir, key, "key", mapper);
            let value_inner = rust_collect_text_keys(ir, element, "value", mapper);
            if key_inner.is_empty() && value_inner.is_empty() {
                String::new()
            } else {
                format!("for (key, value) in {value}.iter() {{ {key_inner} {value_inner} }}")
            }
        }
        TypeIr::Struct(_) | TypeIr::Union(_) => format!("{value}.collect_text_keys(out);"),
        TypeIr::Ref { table, field } => match resolve_ref_key_identity(&ir.tables, table, field) {
            Ok(TableKeyIdentity::Primitive {
                raw_type: TypeIr::Text,
                ..
            }) => format!("out.push({value}.as_text_key());"),
            _ => String::new(),
        },
        TypeIr::Bool
        | TypeIr::I8
        | TypeIr::U8
        | TypeIr::I16
        | TypeIr::U16
        | TypeIr::I32
        | TypeIr::U32
        | TypeIr::I64
        | TypeIr::Duration
        | TypeIr::DateTime
        | TypeIr::F32
        | TypeIr::F64
        | TypeIr::String
        | TypeIr::Enum(_) => String::new(),
    }
}

struct RustTypeMapper<'a> {
    target: &'a str,
    ir: &'a ConfigIr,
    mappings: &'a TypeMappingRegistry,
    options: &'a RustCodegenOptions,
}

impl<'a> RustTypeMapper<'a> {
    fn new(
        target: &'a str,
        ir: &'a ConfigIr,
        mappings: &'a TypeMappingRegistry,
        options: &'a RustCodegenOptions,
    ) -> Self {
        Self {
            target,
            ir,
            mappings,
            options,
        }
    }

    fn type_name(&self, ty: &TypeIr, root_path: &str) -> String {
        if let Some(mapping) = self.mapping(ty) {
            return mapping.type_name;
        }

        match ty {
            TypeIr::Bool => "bool".to_owned(),
            TypeIr::I8 => "i8".to_owned(),
            TypeIr::U8 => "u8".to_owned(),
            TypeIr::I16 => "i16".to_owned(),
            TypeIr::U16 => "u16".to_owned(),
            TypeIr::I32 => "i32".to_owned(),
            TypeIr::U32 => "u32".to_owned(),
            TypeIr::I64 => "i64".to_owned(),
            TypeIr::Duration => "std::time::Duration".to_owned(),
            TypeIr::DateTime => match self.options.datetime_type {
                RustDateTimeType::SystemTime => "std::time::SystemTime".to_owned(),
                RustDateTimeType::Chrono => "chrono::DateTime<chrono::Utc>".to_owned(),
            },
            TypeIr::F32 => "f32".to_owned(),
            TypeIr::F64 => "f64".to_owned(),
            TypeIr::String => match self.options.string_storage {
                RustStringStorage::Owned => "String".to_owned(),
                RustStringStorage::Arc => "std::sync::Arc<str>".to_owned(),
            },
            TypeIr::Text => format!("{root_path}::runtime::TextKey"),
            TypeIr::Enum(name) | TypeIr::Struct(name) | TypeIr::Union(name) => {
                rust_named_type_path(name, root_path)
            }
            TypeIr::List(element) => format!("Vec<{}>", self.type_name(element, root_path)),
            TypeIr::Set(element) => {
                format!(
                    "std::collections::HashSet<{}>",
                    self.type_name(element, root_path)
                )
            }
            TypeIr::Map { key, value } => {
                format!(
                    "std::collections::HashMap<{}, {}>",
                    self.type_name(key, root_path),
                    self.type_name(value, root_path)
                )
            }
            TypeIr::Array { element, len } => {
                format!("[{}; {len}]", self.type_name(element, root_path))
            }
            TypeIr::Ref { table, field } => {
                let identity = resolve_ref_key_identity(&self.ir.tables, table, field)
                    .unwrap_or_else(|error| {
                        panic!("validated ref key `{table}.{field}` should resolve: {error}")
                    });
                self.key_identity_type_name(identity, root_path)
            }
            TypeIr::Optional(element) => self
                .mapping(element)
                .and_then(|mapping| mapping.nullable_type_name)
                .unwrap_or_else(|| format!("Option<{}>", self.type_name(element, root_path))),
        }
    }

    fn key_param_type(&self, ty: &TypeIr, root_path: &str) -> String {
        if let TypeIr::Ref { table, field } = ty {
            let identity = resolve_ref_key_identity(&self.ir.tables, table, field)
                .expect("validated ref key should resolve");
            return self.key_identity_param_type(identity, root_path);
        }
        let type_name = self.local_table_key_type(ty, root_path);
        if type_name == "String" || type_name == "std::sync::Arc<str>" {
            "str".to_owned()
        } else {
            type_name
        }
    }

    fn local_table_key_type(&self, ty: &TypeIr, root_path: &str) -> String {
        match ty {
            TypeIr::Ref { table, field } => {
                let identity = resolve_ref_key_identity(&self.ir.tables, table, field)
                    .unwrap_or_else(|error| {
                        panic!("validated ref key `{table}.{field}` should resolve: {error}")
                    });
                self.key_identity_type_name(identity, root_path)
            }
            _ => self.type_name(ty, root_path),
        }
    }

    fn key_type_is_copy(&self, ty: &TypeIr) -> bool {
        match ty {
            TypeIr::Bool
            | TypeIr::I8
            | TypeIr::U8
            | TypeIr::I16
            | TypeIr::U16
            | TypeIr::I32
            | TypeIr::U32
            | TypeIr::I64
            | TypeIr::Duration
            | TypeIr::DateTime
            | TypeIr::F32
            | TypeIr::F64
            | TypeIr::Enum(_) => self.mapping(ty).is_none(),
            TypeIr::Ref { table, field } => resolve_ref_key_identity(&self.ir.tables, table, field)
                .is_ok_and(|identity| self.key_identity_is_copy(identity)),
            TypeIr::Optional(element) => self.key_type_is_copy(element),
            TypeIr::String
            | TypeIr::Text
            | TypeIr::Struct(_)
            | TypeIr::Union(_)
            | TypeIr::List(_)
            | TypeIr::Set(_)
            | TypeIr::Map { .. }
            | TypeIr::Array { .. } => false,
        }
    }

    fn imports(&self, ty: &TypeIr) -> Vec<String> {
        self.mappings.imports_for(self.target, self.ir, ty)
    }

    fn mapping(&self, ty: &TypeIr) -> Option<TypeMapping> {
        self.mappings.map_type(TypeMappingContext {
            target: self.target,
            ir: self.ir,
            ty,
        })
    }

    fn wrap_decode(&self, ty: &TypeIr, base_expr: String) -> String {
        self.mapping(ty)
            .map(|mapping| mapping.wrap_decode(&base_expr))
            .unwrap_or(base_expr)
    }

    fn key_identity_type_name(&self, identity: TableKeyIdentity<'_>, root_path: &str) -> String {
        match identity {
            TableKeyIdentity::Primitive { table, field, .. } => format!(
                "{root_path}::{}::{}",
                schema_module_path(&table.name).replace('/', "::"),
                strong_key_name(table, field)
            ),
            TableKeyIdentity::Enum { name } => {
                self.type_name(&TypeIr::Enum(name.to_owned()), root_path)
            }
        }
    }

    fn key_identity_param_type(&self, identity: TableKeyIdentity<'_>, root_path: &str) -> String {
        if self.key_identity_is_string_like(identity) {
            "str".to_owned()
        } else {
            self.key_identity_type_name(identity, root_path)
        }
    }

    fn key_identity_is_copy(&self, identity: TableKeyIdentity<'_>) -> bool {
        match identity {
            TableKeyIdentity::Primitive { raw_type, .. } => self.key_type_is_copy(raw_type),
            TableKeyIdentity::Enum { name } => {
                self.mapping(&TypeIr::Enum(name.to_owned())).is_none()
            }
        }
    }

    fn key_identity_is_string_like(&self, identity: TableKeyIdentity<'_>) -> bool {
        matches!(
            identity,
            TableKeyIdentity::Primitive {
                raw_type: TypeIr::String | TypeIr::Text,
                ..
            }
        )
    }
}

fn rust_decode_expr(
    ir: &ConfigIr,
    ty: &TypeIr,
    mapper: &RustTypeMapper<'_>,
    root_path: &str,
) -> String {
    match ty {
        TypeIr::Enum(name) | TypeIr::Struct(name) | TypeIr::Union(name) => mapper.wrap_decode(
            ty,
            format!(
                "<{} as {root_path}::runtime::SoraDecode>::decode(reader)?",
                rust_named_type_path(name, root_path)
            ),
        ),
        TypeIr::List(element) => format!(
            "{{ let len = reader.read_var_u32()? as usize; let mut values = Vec::with_capacity(len); for _ in 0..len {{ values.push({}); }} values }}",
            rust_decode_expr(ir, element, mapper, root_path)
        ),
        TypeIr::Set(element) => format!(
            "{{ let len = reader.read_var_u32()? as usize; let mut values = std::collections::HashSet::with_capacity(len); for _ in 0..len {{ values.insert({}); }} values }}",
            rust_decode_expr(ir, element, mapper, root_path)
        ),
        TypeIr::Map { key, value } => format!(
            "{{ let len = reader.read_var_u32()? as usize; let mut values = std::collections::HashMap::with_capacity(len); for _ in 0..len {{ values.insert({}, {}); }} values }}",
            rust_decode_expr(ir, key, mapper, root_path),
            rust_decode_expr(ir, value, mapper, root_path)
        ),
        TypeIr::Array { element, len } => {
            let element_type = mapper.type_name(element, root_path);
            format!(
                "{{ let mut values = Vec::with_capacity({len}); let actual_len = reader.read_var_u32()? as usize; if actual_len != {len} {{ return Err({root_path}::runtime::SoraReadError::new(format!(\"expected array length {len}, got {{}}\", actual_len))); }} for _ in 0..{len} {{ values.push({}); }} values.try_into().map_err(|values: Vec<{element_type}>| {root_path}::runtime::SoraReadError::new(format!(\"expected array length {len}, got {{}}\", values.len())))? }}",
                rust_decode_expr(ir, element, mapper, root_path)
            )
        }
        TypeIr::Ref { table, field } => {
            let identity =
                resolve_ref_key_identity(&ir.tables, table, field).unwrap_or_else(|error| {
                    panic!("validated ref key `{table}.{field}` should resolve: {error}")
                });
            match identity {
                TableKeyIdentity::Primitive { .. } => {
                    let type_name = mapper.key_identity_type_name(identity, root_path);
                    format!("<{type_name} as {root_path}::runtime::SoraDecode>::decode(reader)?")
                }
                TableKeyIdentity::Enum { name } => {
                    let enum_ty = TypeIr::Enum(name.to_owned());
                    mapper.wrap_decode(
                        &enum_ty,
                        format!(
                            "<{} as {root_path}::runtime::SoraDecode>::decode(reader)?",
                            rust_named_type_path(name, root_path)
                        ),
                    )
                }
            }
        }
        TypeIr::Optional(element) => {
            format!(
                "match reader.read_u8()? {{ 0 => None, 1 => Some({}), value => return Err({root_path}::runtime::SoraReadError::new(format!(\"invalid option presence {{}}\", value))), }}",
                rust_decode_expr(ir, element, mapper, root_path)
            )
        }
        _ => format!(
            "<{} as {root_path}::runtime::SoraDecode>::decode(reader)?",
            mapper.type_name(ty, root_path)
        ),
    }
}

fn rust_named_type_path(name: &str, root_path: &str) -> String {
    format!(
        "{root_path}::{}::{}",
        schema_module_path(name).replace('/', "::"),
        schema_local_name(name)
    )
}

fn strong_key_name(table: &sora_ir::model::TableIr, field: &sora_ir::model::FieldIr) -> String {
    format!(
        "{}{}",
        schema_local_name(&table.name).to_pascal_case(),
        field.name.to_pascal_case()
    )
}

fn is_const_raw_type(ty: &TypeIr) -> bool {
    matches!(
        ty,
        TypeIr::Bool
            | TypeIr::I8
            | TypeIr::U8
            | TypeIr::I16
            | TypeIr::U16
            | TypeIr::I32
            | TypeIr::U32
            | TypeIr::I64
            | TypeIr::Duration
    )
}

fn rust_module_root(module_path: &str) -> String {
    std::iter::repeat_n("super", module_path.split('/').count())
        .collect::<Vec<_>>()
        .join("::")
}

fn rust_container_type(mode: TableModeIr, row_type: &str, key_type: Option<&str>) -> String {
    match mode {
        TableModeIr::List => format!("Vec<{row_type}>"),
        TableModeIr::Map => match key_type {
            Some(key_type) => format!("SoraMap<{key_type}, {row_type}>"),
            None => format!("Vec<{row_type}>"),
        },
        TableModeIr::Singleton => row_type.to_owned(),
    }
}

fn rust_string_storage_name(storage: RustStringStorage) -> &'static str {
    match storage {
        RustStringStorage::Owned => "owned",
        RustStringStorage::Arc => "arc",
    }
}

fn rust_datetime_type_name(datetime_type: RustDateTimeType) -> &'static str {
    match datetime_type {
        RustDateTimeType::SystemTime => "system_time",
        RustDateTimeType::Chrono => "chrono",
    }
}

fn rust_serde_with(ty: &TypeIr, options: &RustCodegenOptions, root_path: &str) -> Option<String> {
    match ty {
        TypeIr::Map { .. } => Some(format!("{root_path}::runtime::serde_map_pairs")),
        TypeIr::Optional(element) if matches!(element.as_ref(), TypeIr::Map { .. }) => {
            Some(format!("{root_path}::runtime::serde_optional_map_pairs"))
        }
        TypeIr::DateTime => Some(format!(
            "{root_path}::runtime::{}",
            match options.datetime_type {
                RustDateTimeType::SystemTime => "serde_system_time_millis",
                RustDateTimeType::Chrono => "serde_chrono_datetime_millis",
            }
        )),
        _ => None,
    }
}

#[cfg(test)]
mod namespace_tests {
    use super::*;
    use sora_ir::normalize::normalize_schema;
    use sora_schema::model::ProjectSchema;
    use std::process::Command;

    #[test]
    fn generates_nested_rust_modules() {
        let schema: ProjectSchema = toml::from_str(
            r#"
project = { id = "game_config" }
groups = { common = { default = true } }
views = { default = { contract = "game_config/default", groups = ["common"] } }

[[enums]]
name = "Status"
values = [{ id = 0, name = "Active" }]

[[structs]]
name = "common.Reward"

[[structs.fields]]
name = "amount"
type = "i32"

[[tables]]
id = "items.item"
name = "items.Item"
mode = "map"
key = "id"

[[tables.fields]]
name = "id"
type = "string"

[[tables.fields]]
name = "reward"
type = "struct<common.Reward>"

[[tables.fields]]
name = "status"
type = "enum<Status>"
"#,
        )
        .unwrap();
        let ir = normalize_schema(schema).unwrap();
        let out = std::env::temp_dir().join("sora-codegen-rust-namespace-test");
        let _ = std::fs::remove_dir_all(&out);

        RustCodeGenerator
            .generate_with_options(&ir, RustCodegenOptions::default(), &out)
            .unwrap();

        assert!(out.join("common/reward.rs").exists());
        assert!(out.join("items/item.rs").exists());
        assert!(out.join("status.rs").exists());
        assert!(out.join("common/mod.rs").exists());
        assert!(out.join("items/mod.rs").exists());
        let root = std::fs::read_to_string(out.join("mod.rs")).unwrap();
        let items = std::fs::read_to_string(out.join("items/item.rs")).unwrap();
        let status = std::fs::read_to_string(out.join("status.rs")).unwrap();
        let items_mod = std::fs::read_to_string(out.join("items/mod.rs")).unwrap();
        assert!(root.contains("pub mod common;"));
        assert!(root.contains("pub mod items;"));
        assert!(items.contains("pub reward: super::super::common::reward::Reward"));
        assert!(items.contains("impl super::super::runtime::SoraDecode for Item"));
        assert!(status.contains("impl super::runtime::SoraDecode for Status"));
        assert!(!items.contains("crate::"));
        assert!(!status.contains("crate::"));
        assert!(items_mod.contains("pub mod item;"));
        assert!(!items_mod.contains("pub use"));
        let _ = std::fs::remove_dir_all(out);
    }

    #[test]
    fn only_renames_fields_when_the_schema_and_rust_names_differ() {
        let schema: ProjectSchema = toml::from_str(
            r#"
project = { id = "game_config" }
groups = { common = { default = true } }
views = { default = { contract = "game_config/default", groups = ["common"] } }

[[structs]]
name = "Cost"

[[structs.fields]]
name = "entry_cost"
type = "i32"

[[structs.fields]]
name = "displayName"
type = "string"

[[unions]]
name = "Action"
tag = "type"

[[unions.variants]]
name = "Charge"

[[unions.variants.fields]]
name = "resource_id"
type = "i32"

[[unions.variants.fields]]
name = "resourceCount"
type = "i32"
"#,
        )
        .unwrap();
        let ir = normalize_schema(schema).unwrap();
        let out = std::env::temp_dir().join("sora-codegen-rust-serde-rename-test");
        let _ = std::fs::remove_dir_all(&out);

        RustCodeGenerator
            .generate_with_options(&ir, RustCodegenOptions::default(), &out)
            .unwrap();

        let cost = std::fs::read_to_string(out.join("cost.rs")).unwrap();
        assert!(cost.contains("pub entry_cost: i32"));
        assert!(!cost.contains("#[serde(rename = \"entry_cost\")]"));
        assert!(cost.contains("#[serde(rename = \"displayName\")]\n    pub display_name: String"));

        let action = std::fs::read_to_string(out.join("action.rs")).unwrap();
        assert!(action.contains("resource_id: i32"));
        assert!(!action.contains("#[serde(rename = \"resource_id\")]"));
        assert!(
            action.contains("#[serde(rename = \"resourceCount\")]\n        resource_count: i32")
        );

        let _ = std::fs::remove_dir_all(out);
    }

    #[test]
    fn strong_table_keys_propagate_through_refs_and_compile() {
        let schema: ProjectSchema = toml::from_str(
            r#"
project = { id = "strong_keys" }
groups = { common = { default = true } }
views = { default = { contract = "strong_keys/default", groups = ["common"] } }

[[enums]]
name = "Kind"
values = [{ id = 0, name = "Default" }]

[[structs]]
name = "RefHolder"

[[structs.fields]]
name = "biome"
type = "ref<world.Biome.id>"

[[unions]]
name = "RefChoice"
tag = "type"

[[unions.variants]]
name = "Biome"

[[unions.variants.fields]]
name = "id"
type = "ref<world.Biome.id>"

[[tables]]
id = "world.biome"
name = "world.Biome"
mode = "map"
key = "id"

[[tables.fields]]
name = "id"
type = "u32"

[[tables]]
id = "world.terrain"
name = "world.Terrain"
mode = "map"
key = "id"

[[tables.fields]]
name = "id"
type = "u32"

[[tables]]
id = "asset"
name = "Asset"
mode = "map"
key = "code"

[[tables.fields]]
name = "code"
type = "string"

[[tables]]
id = "time_point"
name = "TimePoint"
mode = "map"
key = "at"

[[tables.fields]]
name = "at"
type = "datetime"

[[tables]]
id = "localized"
name = "Localized"
mode = "map"
key = "key"

[[tables.fields]]
name = "key"
type = "text"

[[tables]]
id = "timeout"
name = "Timeout"
mode = "map"
key = "duration"

[[tables.fields]]
name = "duration"
type = "duration"

[[tables]]
id = "biome_alias"
name = "BiomeAlias"
mode = "map"
key = "id"

[[tables.fields]]
name = "id"
type = "ref<world.Biome.id>"

[[tables]]
id = "kind_lookup"
name = "KindLookup"
mode = "map"
key = "kind"

[[tables.fields]]
name = "kind"
type = "enum<Kind>"

[[tables]]
id = "consumer"
name = "Consumer"
mode = "list"

[[tables.fields]]
name = "biome"
type = "ref<world.Biome.id>"

[[tables.fields]]
name = "maybe_biome"
type = "optional<ref<world.Biome.id>>"

[[tables.fields]]
name = "biomes"
type = "list<ref<world.Biome.id>>"

[[tables.fields]]
name = "biome_set"
type = "set<ref<world.Biome.id>>"

[[tables.fields]]
name = "biome_pair"
type = "array<ref<world.Biome.id>,2>"

[[tables.fields]]
name = "biome_map"
type = "map<string,ref<world.Biome.id>>"

[[tables.fields]]
name = "holder"
type = "struct<RefHolder>"

[[tables.fields]]
name = "choice"
type = "union<RefChoice>"
"#,
        )
        .unwrap();
        let ir = normalize_schema(schema).unwrap();
        let out = std::env::temp_dir().join(format!(
            "sora-codegen-rust-strong-key-test-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&out);

        RustCodeGenerator
            .generate_with_options(
                &ir,
                RustCodegenOptions {
                    runtime_format: RuntimeFormat::Json,
                    string_storage: RustStringStorage::Arc,
                    crate_options: Some(RustCrateOptions {
                        name: "strong-keys".to_owned(),
                        ..Default::default()
                    }),
                    ..Default::default()
                },
                &out,
            )
            .unwrap();

        let biome = std::fs::read_to_string(out.join("src/world/biome.rs")).unwrap();
        let terrain = std::fs::read_to_string(out.join("src/world/terrain.rs")).unwrap();
        let asset = std::fs::read_to_string(out.join("src/asset.rs")).unwrap();
        let time_point = std::fs::read_to_string(out.join("src/time_point.rs")).unwrap();
        let localized = std::fs::read_to_string(out.join("src/localized.rs")).unwrap();
        let alias = std::fs::read_to_string(out.join("src/biome_alias.rs")).unwrap();
        let kind_lookup = std::fs::read_to_string(out.join("src/kind_lookup.rs")).unwrap();
        let consumer = std::fs::read_to_string(out.join("src/consumer.rs")).unwrap();
        let holder = std::fs::read_to_string(out.join("src/ref_holder.rs")).unwrap();
        let choice = std::fs::read_to_string(out.join("src/ref_choice.rs")).unwrap();

        assert!(biome.contains("pub struct BiomeId("));
        assert!(biome.contains("pub id: BiomeId"));
        assert!(biome.contains("rows: SoraMap<BiomeId, Biome>"));
        assert!(biome.contains("type Key = BiomeId"));
        assert!(terrain.contains("pub struct TerrainId("));
        assert!(asset.contains("pub struct AssetCode("));
        assert!(asset.contains("impl std::borrow::Borrow<str> for AssetCode"));
        assert!(asset.contains("pub fn get_str(&self, key: &str)"));
        assert!(time_point.contains("pub struct TimePointAt("));
        assert!(time_point.contains("serde_system_time_millis"));
        assert!(localized.contains("pub struct LocalizedKey("));
        assert!(localized.contains("pub fn as_text_key(&self)"));
        assert!(!alias.contains("pub struct BiomeAliasId("));
        assert!(alias.contains("pub id: super::world::biome::BiomeId"));
        assert!(kind_lookup.contains("pub kind: super::kind::Kind"));
        assert!(!kind_lookup.contains("pub struct KindLookupKind("));
        assert!(consumer.contains("pub biome: super::world::biome::BiomeId"));
        assert!(consumer.contains("Option<super::world::biome::BiomeId>"));
        assert!(consumer.contains("Vec<super::world::biome::BiomeId>"));
        assert!(consumer.contains("HashSet<super::world::biome::BiomeId>"));
        assert!(consumer.contains("[super::world::biome::BiomeId; 2]"));
        assert!(consumer.contains("HashMap<std::sync::Arc<str>, super::world::biome::BiomeId>"));
        assert!(holder.contains("pub biome: super::world::biome::BiomeId"));
        assert!(choice.contains("id: super::world::biome::BiomeId"));

        std::fs::create_dir_all(out.join("tests")).unwrap();
        std::fs::write(
            out.join("tests/strong_keys.rs"),
            r#"
use std::{any::TypeId, collections::HashMap};
use strong_keys::{
    asset::AssetCode,
    localized::LocalizedKey,
    runtime::{SoraDecode, SoraReader, TextKey},
    time_point::TimePointAt,
    world::{biome::BiomeId, terrain::TerrainId},
};

#[test]
fn keys_are_nominal_transparent_and_decodable() {
    assert_ne!(TypeId::of::<BiomeId>(), TypeId::of::<TerrainId>());
    assert_eq!(serde_json::to_string(&BiomeId::from_raw(7)).unwrap(), "7");
    assert_eq!(serde_json::from_str::<BiomeId>("7").unwrap().raw(), 7);

    let mut reader = SoraReader::new(&[7], &[]);
    assert_eq!(BiomeId::decode(&mut reader).unwrap().raw(), 7);
    assert!(reader.is_finished());

    let code = AssetCode::from_raw(std::sync::Arc::from("sword"));
    let mut values = HashMap::new();
    values.insert(code, 1);
    assert_eq!(values.get("sword"), Some(&1));

    let at = TimePointAt::from_raw(std::time::UNIX_EPOCH + std::time::Duration::from_millis(42));
    assert_eq!(serde_json::to_string(&at).unwrap(), "42");

    let text = LocalizedKey::from_raw(TextKey(std::sync::Arc::from("ui.title")));
    assert_eq!(text.as_str(), "ui.title");
    assert_eq!(serde_json::to_string(&text).unwrap(), "\"ui.title\"");
}
"#,
        )
        .unwrap();
        let status = Command::new(env!("CARGO"))
            .args(["test", "--offline", "--quiet"])
            .env("CARGO_TARGET_DIR", out.join("target"))
            .current_dir(&out)
            .status()
            .unwrap();
        assert!(status.success());

        let _ = std::fs::remove_dir_all(out);
    }

    #[test]
    fn rejects_strong_key_name_collisions() {
        let schema: ProjectSchema = toml::from_str(
            r#"
project = { id = "collision" }
groups = { common = { default = true } }
views = { default = { contract = "collision/default", groups = ["common"] } }

[[tables]]
id = "item"
name = "Item"
mode = "map"
key = "table"

[[tables.fields]]
name = "table"
type = "u32"
"#,
        )
        .unwrap();
        let ir = normalize_schema(schema).unwrap();
        let out = std::env::temp_dir().join("sora-codegen-rust-key-collision-test");
        let error = RustCodeGenerator
            .generate_with_options(&ir, RustCodegenOptions::default(), &out)
            .unwrap_err();
        assert!(error.to_string().contains("ItemTable"));
        assert!(error.to_string().contains("conflicts"));
    }
}
